### PR TITLE
Added Win Sysmon LogName

### PR DESCRIPTION
**Pull request by fryguy04**

### CODE REVIEW

**Comment by fryguy04** [comment]
Added LogName so that _powershell_ backend works as intended. 

Compile command example:
`python3 ./tools/sigmac -t powershell ./rules/windows/process_creation/<RULE>.yml`

Without it you get ... (which fails)
`Get-WinEvent | where {($_.ID -eq "1" -and $_.message -match "Image.*.*\\calc.*") }`

With this pull request you get ... (which succeeds) 
`Get-WinEvent -LogName "Microsoft-Windows-Sysmon/Operational" | where {($_.ID -eq "1" -and $_.message -match "Image.*.*\\calc.*") }`

NOTE: Don't believe this would adversely affect other compilations, but with a few tests it looked fine

**Comment by frack113** [comment]
It is just you don't use the correct command

```bash
python sigmac -t powershell -c config/generic/sysmon.yml ../rules/windows/process_creation/process_creation_sdelete.yml
Get-WinEvent | where {($_.ID -eq "1" -and $_.message -match "OriginalFileName.*sdelete.exe" -and  -not (($_.message -match "CommandLine.*.* -h.*" -or $_.message -match "CommandLine.*.* -c.*" -or $_.message -match "CommandLine.*.* -z.*" -or $_.message -match "CommandLine.*.* /?.*"))) } | select TimeCreated,Id,RecordId,ProcessId,MachineName,Message
```
with `-c config/powershell.yml`
```bash
 python sigmac -t powershell -c config/generic/sysmon.yml -c config/powershell.yml ../rules/windows/process_creation/process_creation_sdelete.yml 
Get-WinEvent -LogName Microsoft-Windows-Sysmon/Operational | where {(($_.ID -eq "1") -and $_.message -match "OriginalFileName.*sdelete.exe" -and  -not (($_.message -match "CommandLine.*.* -h.*" -or $_.message -match "CommandLine.*.* -c.*" -or $_.message -match "CommandLine.*.* -z.*" -or $_.message -match "CommandLine.*.* /?.*"))) } | select TimeCreated,Id,RecordId,ProcessId,MachineName,Message
```

If you put LogName in sysmon.yml you kill the other backend  mapping example :
```
((winlog.event_id:"1" AND LogName:"Microsoft\-Windows\-Sysmon\/Operational" AND winlog.channel:"Microsoft\-Windows\-Sysmon\/Operational") AND winlog.event_data.OriginalFileName:"sdelete.exe" AND (NOT (winlog.event_data.CommandLine.keyword:(*\ \-h* OR *\ \-c* OR *\ \-z* OR *\ \/?*))
```

**Comment by Karneades** [comment]
Yes, use the PowerShell config. It's also recommended for each other backend to use the explicit config. Changing the Sysmon config is wrong here.

**Comment by frack113** [comment]
Hi, do you agree to close ?
Thanks

**Comment by fryguy04** [comment]
Thanks for showing me the right way … I’ll give it a test today and report back (close this if all works out)

**Comment by fryguy04** [comment]
Just tested and using the `-c config/powershell.yml` worked as you said. Thanks for your help. Closing

**Pull request closed without merging**
