### PR TITLE
Making a derived detection for system/application/security event logs…

### PR DESCRIPTION
**Pull request by redsand**
… being cleared, vs any in general. fp due to custom applications clearing their eventlog

### CODE REVIEW

**Comment by Neo23x0** [comment]
Isn't the message something added by the Windows Event Viewer upon inspection? 
It doesn't appear in the XML and therefore I don't think we can match on that. 

Screenshot 2022-05-17 213501
Screenshot 2022-05-17 213450

**Comment by redsand** [comment]
It's present in many/most logging solutions.  This is populated by calling the windows api: 
```
EvtFormatMessage(hMetadata, hEvent, 0, 0, NULL, EvtFormatMessageEvent, dwBufferSize, pBuffer, &dwBufferUsed);
```

**Comment by frack113** [comment]
> It's present in many/most logging solutions

So this rule works only for THIS logging solutions

From ETW with WEPExplorer
```
<Event>
   <Id>104</Id>
   <Version>0</Version>
   <Channel>System</Channel>
   <Level>Information</Level>
   <Task>Log clear</Task>
   <Message><![CDATA[ The %3 log file was cleared.]]></Message>
   <Template><![CDATA[
      <template xmlns="http://schemas.microsoft.com/win/2004/08/events">
      <data name="SubjectUserName" inType="win:UnicodeString" outType="xs:string"/>
      <data name="SubjectDomainName" inType="win:UnicodeString" outType="xs:string"/>
      <data name="Channel" inType="win:UnicodeString" outType="xs:string"/>
      <data name="BackupPath" inType="win:UnicodeString" outType="xs:string"/>
    </template>
    ]]></Template>
</Event>
```

so more like 
```yaml
selection2_channel: 
  Message|contains:
        - "System"
        - "Security"
        - "Application"
selection2_missing:    
   Message: null
condition: selection and 1 of selection2_*
```
It should works event if Message do not exist

**Comment by redsand** [comment]
This rule does not need the matching of null/empty content because it's explicitly focused on detecting System, Security and Application.  This rule is derived from d99b79d2-0a6f-4f46-ad8b-260b6e17f982 which covers the null condition.

I believe this rule covers most logging solutions, excluding Sysmon (not available). There may be others.
This is compatible with hawk, splunk, and winlogbeat (elastic) just to name a few.

**Comment by Neo23x0** [comment]
What Frack113 means is that it shouldn't break the detections in the other solutions.

**Comment by frack113** [comment]
Windows 11 french
image

**Comment by secDre4mer** [comment]
Couldn't we add a selection like 

```
selection_channel: 
  Channel:
        - "System"
        - "Security"
        - "Application"
```

to target backends that do not have the message, but use the original XML data instead?

**Comment by Neo23x0** [comment]
So, there are "fp due to custom applications clearing their eventlog" and that's why the first rule does only get a low "level". 
The second rule is somehow more robust because "Windows adds that sentence to the Event" when it clears the Eventlog and other applications don't?

**Comment by redsand** [comment]
> So, there are "fp due to custom applications clearing their eventlog" and that's why the first rule does only get a low "level". The second rule is somehow more robust because "Windows adds that sentence to the Event" when it clears the Eventlog and other applications don't?

The sentence is added/available when the eventlog is cleared, no matter what.  In custom applications, it will list the custom application name.  The second rule is more robust because it matches against the content in the message.  

I hadn't thought about localization of text, which creates another problem.  The origin of this issue stems from the fact that WHICH eventlog channel was cleared is not available in any of the xml event data.

**Comment by redsand** [comment]
I have updated this item to leverage the Channel field.

**Pull request merged**
