### PR TITLE
Add Process Creation of SCR File

### PR DESCRIPTION
**Pull request by securepeacock**
Screen Shot 2022-04-27 at 1 14 54 PM

### CODE REVIEW

**Comment by frack113** [comment]
HI, 
I got FTs when activating one of the windows screensavers.

**Comment by Neo23x0** [comment]
I think this would trigger on every screensaver execution. 

image

**Comment by securepeacock** [comment]
Let me check, is rundll32 the parent of any of those?

**Comment by securepeacock** [comment]
SourceImage="*\rundll32.exe" TargetImage="*.scr"
Screen Shot 2022-04-27 at 2 17 52 PM

**Comment by securepeacock** [comment]
Updated to tune into rundll32 as parent process, I think that should do the trick.

**Comment by Neo23x0** [comment]
That's what a legitimate Screensaver start looks like:

Screenshot 2022-04-27 204221

**Comment by Neo23x0** [comment]
I'd say, I file creation rule would make more sense. An attacker has to write malicious *.scr to disk before executing them and the legitimate screensavers are already stored in the system folders.

**Comment by securepeacock** [comment]
Screen Shot 2022-04-27 at 3 32 25 PM
Hmm, in the lolbas document it can be ran remotely. It is interesting your command line parameter is "desk.cpl,screensave" where both lolbas instances leverage "desk.cpl,InstallScreenSaver". 

Would you say one file write rule and one runddl32 with "desk.cpl,InstallScreenSaver" rule, or just the file write?

**Comment by Neo23x0** [comment]
Sorry, I just saw the PRs not your answer here.

**Pull request closed without merging**
