### PR TITLE
New Rule : Create Remote Thread In Shell Application

### PR DESCRIPTION
**Pull request by fornotes**
### Summary of the Pull Request
New rule to detect process injection into cmd and powershell based on:

- https://research.splunk.com/endpoint/10399c1e-f51e-11eb-b920-acde48001122/
- https://www.binarydefense.com/resources/blog/icedid-gziploader-analysis/

### Changelog
new : Remote Thread Created In Shell Application

### Example Log Event
https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/icedid/simulated_icedid/windows-sysmon.log

### Fixed Issues
N/A

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Review by nasbench — APPROVED** [review]
LGTM.

Note: This might be transferred to hunting in the future. We'll have to see results from testing in the next couple of days.

**Comment by swachchhanda000** [comment]
Hi @nasbench,
 this rule causes so many fps as it gets triggered whenever any program spawn these applications.
 What should we do?

**Comment by nasbench** [comment]
> Hi @nasbench, @frack113 , this rule causes so many fps as it gets triggered whenever any program spawn these applications. What should we do?

As its suggested by my comment months ago. Create a PR and move it to hunting and paste examples of these Fps

**Comment by swachchhanda000** [comment]
> > Hi @nasbench, @frack113 , this rule causes so many fps as it gets triggered whenever any program spawn these applications. What should we do?
> 
> As its suggested by my comment months ago. Create a PR and move it to hunting and paste examples of these Fps

Thanks @nasbench, I have observed fps on other rules with other create remote thread log sourced rules. I will also include them in that PR.

**Pull request merged**
