### PR TITLE
Update pipe_create_mal__cobaltstrike - Additional criteria from Redcanary

### PR DESCRIPTION
**Pull request by Pooch11**
- https://redcanary.com/threat-detection-report/threats/cobalt-strike/ reports new pipenames for cobaltstrike
- quick win to add these names to the criteria list in the same 'startswith' format

### CODE REVIEW

**Comment by Neo23x0** [comment]
I'm not sure if we excluded these prefixes because they caused false positives. I have to check that first.

**Comment by Pooch11** [comment]
> I'm not sure if we excluded these prefixes because they caused false positives. I have to check that first.

Anything I can do to help move this along?  I could try and find more sources indicating these pipe names found in the wild are TP

**Comment by phantinuss** [comment]
We have them in the sysmon-config:
https://github.com/Neo23x0/sysmon-config/blob/master/sysmonconfig-export.xml#L968-L975

I think we should include them.

**Review by phantinuss — APPROVED** [review]

**Comment by phantinuss** [comment]
To be more specific. The pipenames appear legitimately on Windows systems in the exact version without the _. The cobaltstrike profiles make use of them in a form of `\<legitimate-name>_##`

**Comment by a-Pooch** [comment]
> To be more specific. The pipenames appear legitimately on Windows systems in the exact version without the _. The cobaltstrike profiles make use of them in a form of `\<legitimate-name>_##`

Thank you, I've updated the PR again so it can be merged with ease if approved.

**Pull request merged**
