### PR TITLE
Create proc_creation_win_DarkGate_GoogleUpdate.yml

### PR DESCRIPTION
**Pull request by prashanthpulisetti**
### Summary of the Pull Request
This rule alerts on instances of uncommon or suspicious behavior involving the "GoogleUpdate.exe" process, particularly in the context of activities associated with the threat actor group known as "DarkGate." DarkGate is a threat group known for its involvement in cyber-espionage and other malicious activities. The rule focuses on identifying any deviations from normal behavior related to the execution or spawning of "GoogleUpdate.exe," which may indicate potential malicious activity or lateral movement by DarkGate within the network. Detection of such unusual spawning behavior can help security teams respond promptly to potential threats and enhance overall network security.

### Example Log Event
Process Create:
RuleName: -
UtcTime: 2023-10-23 15:01:24.910
ProcessGuid: {8bf1c579-2dc4-6539-1b0e-000000004000}
ProcessId: 7560
Image: C:\Program Files (x86)\Google\Update\GoogleUpdate.exe
FileVersion: 1.3.36.111
Description: Google Installer
Product: Google Update
Company: Google LLC
OriginalFileName: GoogleUpdate.exe
CommandLine: "C:\Program Files (x86)\Google\Update\GoogleUpdate.exe"
CurrentDirectory: C:\ProgramData\rundese\
User: Marvel\Drstrange
LogonGuid: {8bf1c579-2da9-6539-9646-c50300000000}
LogonId: 0x3C54696
TerminalSessionId: 5
IntegrityLevel: High
Hashes: MD5=6BF197B8C7DE4B004C5D6FA415FC7867,SHA256=61A92167587E540275B374890BE8FD0319FE03C4F19CC79A8C2FB6871CF21E73,IMPHASH=7DF1816239C5BC855600D41210406C5B
ParentProcessGuid: {8bf1c579-2dc2-6539-110e-000000004000}
ParentProcessId: 12240
ParentImage: C:\ProgramData\rundese\Autoit3.exe
ParentCommandLine: "C:\ProgramData\rundese\Autoit3.exe" C:\ProgramData\rundese\dfagahe.au3
ParentUser: Marvel\Drstrange

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by nasbench** [comment]
While we accept all types of PRs but please do your due diligence and read the https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md and a little bit about sigma modifiers :)

Also, there are already rules related to DarkGate in the Emerging Threat folder so best put this there.

**Comment by prashanthpulisetti** [comment]
Thanks, @nasbench  for your inputs. How do I move this file to that folder? Or should I remove this file from here and add again their?

**Comment by nasbench** [comment]
> Thanks, @nasbench for your inputs. How do I move this file to that folder? Or should I remove this file from here and add again there?

You move the file similar to how you move a file on windows or linux. You `cut` it if you're on an editor or use  `mv` command on CLI and move it to the folder. Then commit the changes :)

There is a sub folder in the emerging threats folder related to DarkGate. Use the same file convention.

Also we don't use the `*` notation there is the `contains` modifier (look at other rules). And also in this case its best to use the Image field as its always there while the CLI might be missing for some

**Comment by prashanthpulisetti** [comment]
Alright, Thanks @nasbench. I will make changes soon.

**Comment by nasbench** [comment]
Duplicate of #4515

**Pull request closed without merging**
