### PR TITLE
Fixing errs with invoke obfus

### PR DESCRIPTION
**Pull request by redsand**
Fixing order of operations for matching to reduce performance impacts

### CODE REVIEW

**Comment by frack113** [comment]
HI
Or can be change to a more simple way 
```ymal
detection:
    selection:
        EventID: 4697
        ServiceFileName|re: 'thebestregexoftheyear :)"'
    condition: selection
```

**Comment by Neo23x0** [comment]
Please don't change the modified date when only the order in the condition has changed. 
This should have no effect on backends or query results.

**Comment by redsand** [comment]
> Please don't change the modified date when only the order in the condition has changed. This should have no effect on backends or query results - only a performance impact.

You got it! Thanks for the guidance.

**Comment by redsand** [comment]
This has been resolved.  A different PR will be needed to simplify these rules, since there are about 33 in total

**Pull request merged**
