### PR TITLE
Change Evtx Location Used Wevtutil

### PR DESCRIPTION
**Pull request by D3F7A5105**
[Relate to](https://github.com/SigmaHQ/sigma/pull/3853)

### CODE REVIEW

**Comment by nasbench** [comment]
I think the `sl` is required to use this flag. And the `sl` is already covered by this [rule](https://github.com/SigmaHQ/sigma/blob/ac500a1fcffa84712799160c54bb70bd43ab1191/rules/windows/process_creation/proc_creation_win_susp_eventlog_clear.yml#L4).

I think it's best to update that one and only include a new line with `lfn:` in `selection_wevtutil` like this

```yml
 selection_wevtutil:
        Image|endswith: '\wevtutil.exe'
        CommandLine|contains:
            - 'clear-log '          # clears specified log
            - ' cl '                # short version of 'clear-log'
            - 'set-log '            # modifies config of specified log. could be uset to set it to a tiny size
            - ' sl '                # short version of 'set-log'
            - 'lfn:'
```

**Comment by D3F7A5105** [comment]
> I think the `sl` is required to use this flag. And the `sl` is already covered by this [rule](https://github.com/SigmaHQ/sigma/blob/ac500a1fcffa84712799160c54bb70bd43ab1191/rules/windows/process_creation/proc_creation_win_susp_eventlog_clear.yml#L4).
> 
> I think it's best to update that one and only include a new line with `lfn:` in `selection_wevtutil` like this
> 
> ```yaml
>  selection_wevtutil:
>         Image|endswith: '\wevtutil.exe'
>         CommandLine|contains:
>             - 'clear-log '          # clears specified log
>             - ' cl '                # short version of 'clear-log'
>             - 'set-log '            # modifies config of specified log. could be uset to set it to a tiny size
>             - ' sl '                # short version of 'set-log'
>             - 'lfn:'
> ```
yes, "sl or set-log" is required parameter. May be:
```
        CommandLine|contains:
            - 'set-log '            # modifies config of specified log. could be uset to set it to a tiny size
            - ' sl '           
        CommandLine|contains:
            - 'clear-log '     # clears specified log
            - ' cl '                # short version of 'clear-log'
            -  'lfn:'              # locate file log

```

**Comment by nasbench** [comment]
> > I think the `sl` is required to use this flag. And the `sl` is already covered by this [rule](https://github.com/SigmaHQ/sigma/blob/ac500a1fcffa84712799160c54bb70bd43ab1191/rules/windows/process_creation/proc_creation_win_susp_eventlog_clear.yml#L4).
> > I think it's best to update that one and only include a new line with `lfn:` in `selection_wevtutil` like this
> > ```yaml
> >  selection_wevtutil:
> >         Image|endswith: '\wevtutil.exe'
> >         CommandLine|contains:
> >             - 'clear-log '          # clears specified log
> >             - ' cl '                # short version of 'clear-log'
> >             - 'set-log '            # modifies config of specified log. could be uset to set it to a tiny size
> >             - ' sl '                # short version of 'set-log'
> >             - 'lfn:'
> > ```
> 
> yes, "sl or set-log" is required parameter. May be:
> 
> ```
>         CommandLine|contains:
>             - 'set-log '            # modifies config of specified log. could be uset to set it to a tiny size
>             - ' sl '           
>         CommandLine|contains:
>             - 'clear-log '     # clears specified log
>             - ' cl '                # short version of 'clear-log'
>             -  'lfn:'              # locate file log
> ```

Why split? it's the same category so they all should be under the same CLI

**Comment by D3F7A5105** [comment]
> 
Should it turn out like this?
**sl** is required and one of several parameters
```
"sl" AND ("cl" OR "lfn:")
```

**Comment by nasbench** [comment]
> > 
> 
> Should it turn out like this? **sl** is required and one of several parameters
> 
> ```
> "sl" AND ("cl" OR "lfn:")
> ```

No. `cl` can be standalone not `sl` required.

The rule i linked covers the case of setting the log so there is no need for `lfn` in reality. But we add it cause it doesn't cost anything and if for whatever reason `sl` is obfuscated we might catch it via the `lfn`.

So, just update the rule I linked with the "new" flag and update the modified date.

**Review by nasbench — APPROVED** [review]

**Comment by nasbench** [comment]
Thanks for your contribution :)

**Pull request merged**
