### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sreemanshanker**

### CODE REVIEW

**Review by sreemanshanker — COMMENTED** [review]
Suspicious use of headless browser to download files

**Comment by Neo23x0** [comment]
Please always add a reference - in this case: https://twitter.com/mrd0x/status/1478234484881436672?s=12

**Comment by Neo23x0** [comment]
Please don't use a "re" expression but simply "contains|all" instead. 
Also, change the line endings of this and a few other files to match the line breaks that we use in the repo: 

Screenshot 2022-01-04 at 07 09 22

**Comment by Neo23x0** [comment]
Also always add an `id`. See this guide for details: https://github.com/SigmaHQ/sigma/wiki/Rule-Creation-Guide

**Comment by Neo23x0** [comment]
The line breaks are the only unresolved problem. Please fix them.

**Comment by sreemanshanker** [comment]
missed the reference when copying the template - my bad. thanks for fixing it and the other faults.

**Pull request merged**
