### PR TITLE
Add new rule: proc_creation_disable_SEP

### PR DESCRIPTION
**Pull request by krestinichev**
hi, I would like to add a new rule for the first time.
I hope I'm doing everything right.

### CODE REVIEW

**Comment by krestinichev** [comment]
what needs to be done to publish a rule in a shared repository?

**Comment by Neo23x0** [comment]
It needs to be reviewed and corrected.

**Comment by krestinichev** [comment]
I'm sorry, but I don't understand what's wrong with my rule

**Comment by Neo23x0** [comment]
It's in the queue to be reviewed.

**Comment by Neo23x0** [comment]
You can see in the commits what I had to change

**Comment by krestinichev** [comment]
I fully agree with the changes 👍

**Pull request merged**
