### PR TITLE
Redcannary windows

### PR DESCRIPTION
**Pull request by frack113**
It is sunday , forget this one in the VM.
Put win_pc_susp_takeown.yml in the correct folder

### CODE REVIEW

**Comment by Neo23x0** [comment]
Should we add folders of other browser stores as well?

**Comment by frack113** [comment]
Hi,
My first thought was to make a unique rule `browser`, but I've split to be able to select according to its park.
there is already posh_ps_access_to_chrome_login_data.yml
Need to make a update in redcannary and sigma for : 
- firefox
- edge
- ie ?

**Comment by Neo23x0** [comment]
I'd do Firefox and Edge

**Comment by frack113** [comment]
I've add the  firefox test in  [redcannay](https://github.com/redcanaryco/atomic-red-team/pull/1750)

**Comment by Neo23x0** [comment]
But the rule still looks for Opera's folder only?

**Comment by frack113** [comment]
I have go to 1 rule  per browser as if you manage your park you know what is normally installed.
Or change  to `posh_ps_access_to_browser_login_data.yml` and add other folder.
I have mixed feelings.

**Review by Neo23x0 — APPROVED** [review]

**Pull request merged**
