### PR TITLE
Create process_creation_rundll32_with_control_rundll.yml

### PR DESCRIPTION
**Pull request by BlackB0lt**

### CODE REVIEW

**Comment by Neo23x0** [comment]
Who has set that status to `stable`?

**Comment by BlackB0lt** [comment]
> Who has set that status to `stable`?

I do, refer to https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1218.002/atomic_red_team/windows-sysmon.log

**Comment by Neo23x0** [comment]
I think this rule would trigger every time a users opens a `.cpl` file

**Comment by Neo23x0** [comment]
Also : 
https://www.tenforums.com/tutorials/77458-rundll32-commands-list-windows-10-a.html

**Comment by BlackB0lt** [comment]
> Also : https://www.tenforums.com/tutorials/77458-rundll32-commands-list-windows-10-a.html

Ok, I see. Thank you

**Pull request closed without merging**
