### PR TITLE
feat: new rule for persistence using Office startup

### PR DESCRIPTION
**Pull request by secDre4mer**

### CODE REVIEW

**Comment by Neo23x0** [comment]
I think there is an overlapping rule. Maybe they can be merged. 
https://github.com/SigmaHQ/sigma/pull/3099

**Comment by secDre4mer** [comment]
> I think there is an overlapping rule. Maybe they can be merged.

There are a couple of differences, but I agree that the basic idea is the same: 
- The other rule filters out word documents, which this rule explicitly looks for
- This rule filters out Office programs

What was the reasoning for filtering out Word resources? I don't quite understand from the discussion in the PR. Aren't the Word specific files exactly how persistence is achieved?

**Comment by frack113** [comment]
Hello,
I think the 2 rules are complementary.
My rule detect the behavior of maldoc that drop binary files in startup (here "ket.t"  but by \WINWORD.EXE)
Your rule detect a legal file but not by legal application.

**Comment by Neo23x0** [comment]
You're right. I just took a quick glimpse this morning. (still on vacation)

**Pull request merged**
