### PR TITLE
Token obfuscation regex fix

### PR DESCRIPTION
**Pull request by peterydzynski**
### Summary of the Pull Request
The final regex in the `Powershell Token Obfuscation - Process Creation` rule was fairly broad and would catch a number of unintended cases. It was also not case insensitive and as such missed some cases. If necessary, I am happy to provide screenshots of my tests demonstrating the unintended functionality of the original implementation and the improvements contained in this PR.

Additionally I fixed two dead links in the PR template and in the contributing readme. 

### Changelog
update: Powershell Token Obfuscation - Process Creation - Optimized used regex
update: Powershell Token Obfuscation - Powershell - Optimized used regex
chore: Fixed SigmaHQ conventions broken links

### Example Log Event
image
image

```
Should not match: ${eeee`:path}
Should not match: ${vn`e:path}
Should not match: ${env:p`}
Should not match: ${e`:p`}
Intended match: ${e`Nv:pATh}
Intended match: ${ENV:PAT`H}
```

### Fixed Issues
N/A

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by nasbench** [comment]
Hey @peterydzynski and thanks for the contribution. Can you please provide these unintended matches for documentation purposes as well as update the modified field since you modified the detection section.

**Comment by peterydzynski** [comment]
@nasbench Updated the modified date! Whats the best way for me to provide the unintended detections? Comment on this PR or something more official?

**Comment by nasbench** [comment]
> @nasbench Updated the modified date! Whats the best way for me to provide the unintended detections? Comment on this PR or something more official?

Just put it here in PR for now.

**Comment by peterydzynski** [comment]
image

image


Tests:

```
Should not match: ${eeee`:path}
Should not match: ${vn`e:path}
Should not match: ${env:p`}
Should not match: ${e`:p`}
Intended match: ${e`Nv:pATh}
Intended match: ${ENV:PAT`H}
```

**Review by nasbench — APPROVED** [review]

**Review by frack113 — APPROVED** [review]

**Pull request merged**
