### PR TITLE
Rule: ISO file creation in temporary folders, outlook and zip

### PR DESCRIPTION
**Pull request by Sam0x90**

### CODE REVIEW

**Comment by Neo23x0** [comment]
I like it.

**Comment by wagga40** [comment]
Nice one, I think wildcard should be avoided. 
I think, when it is possible, startswith and endswith give better results with legacy converter.

**Comment by Neo23x0** [comment]
I've made the changes

**Comment by frack113** [comment]
Can be like this
```yaml
   selection_end:
        TargetFilename|endswith: '.iso'
   selection_path:
        - TargetFilename|contains|all:
             - '\AppData\Local\Temp\'
             - '.zip\'
        - TargetFilename|contains: '\AppData\Local\Microsoft\Windows\INetCache\Content.Outlook\'
    condition: all of selection_*
```

**Comment by Sam0x90** [comment]
Indeed better like this, thanks both!

**Comment by Neo23x0** [comment]
I had to change the file name to `file_event_win_iso_file_mount.yml`

**Pull request merged**
