### PR TITLE
rule: myjino github repo compromise

### PR DESCRIPTION
**Pull request by Neo23x0**
https://twitter.com/stephenlacy/status/1554697077430505473?s=20&t=nPmspxUe6162gA55VJzh-Q

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
What repo compromise? Most of those repos if not all where forks and GitHub deleted them within a few hours. If they would have been compromised GitHub wouldn't have deleted them no questions asked.

**Comment by Neo23x0** [comment]
> What repo compromise?

Yes, good question. Can we be sure that not a single request was pulled? 

> Most of those repos if not all where forks and GitHub deleted them within a few hours.

Most? How many? What about the rest?

> If they would have been compromised GitHub wouldn't have deleted them no questions asked.

Do you work for Github? Do all compromised repositories get immediately deleted? How does Github detect a compromise?

**Comment by Neo23x0** [comment]
Official statement published on 4:55pm CEST

https://twitter.com/GitHubSecurity/status/1554843443200806913

**Comment by SuperSandro2000** [comment]
> Can we be sure that not a single request was pulled?

As long as there is no concrete evidence we shouldn't take about a compromise but a potential compromise. 

> Most? How many? What about the rest?

The screenshot on twitter showed initially over 35k results. At the time of my comment that went already down to a few hundred.

> Do you work for Github? Do all compromised repositories get immediately deleted? How does Github detect a compromise?

No but I don't want to believe that GitHub would delete a repository completely without notice if it got compromised. More likely it would be restored or quarantined. Detecting this concrete  attack should be pretty easy because the URL was the same and the code was also very similar. I am also pretty sure that from internal metrics they can correlate more repositories.

**Comment by Neo23x0** [comment]
> The screenshot on twitter showed initially over 35k results. At the time of my comment that went already down to a few hundred.

I don't understand your comment on a pull request that was merged very early this morning. Did you just post it to piss me off?

**Comment by SuperSandro2000** [comment]
Not at all. I just dislike that this is being framed as a compromise with no evidence of any.

**Comment by Neo23x0** [comment]
"is" or "has been" in that commit. It isn't anymore. But at the time of the commit, it looked like it.

**Pull request merged**
