### PR TITLE
MacOS rule filter for wifivelocityd false positives

### PR DESCRIPTION
**Pull request by peterydzynski**
### Summary of the Pull Request
Added a filter to exclude hits where the parent process is `wifivelocityd` which is a benign MacOS system utility that collects wifi metrics. 

### Changelog
fix: System Network Discovery - macOS  -  Add additional filter for `wifivelocityd`

### Example Log Event

```json
{
  "host": {
    "chassis_type": "Other",
    "hostname": "",
    "first_seen": "2022-06-17T22:15:52.000Z",
    "system": {
      "product_name": "MacBookPro18,3",
      "manufacturer": "Apple Inc."
    },
    "os": {
      "platform_original": "macos",
      "full_original": "Sonoma (14)",
      "type": "macos",
      "platform": "Mac OS",
      "full": "Mac OS 14"
    },
    "local_time": "2024-08-11T13:46:24.000Z",
    "ip": [
      ""
    ],
    "name": "",
    "id": "4a577aaaa28d40c385b324b576492fff",
    "external_ip": [
      ""
    ]
  },
  "crowdstrike": {
    "MachOSubType": "1",
    "SVGID": "0",
    "EnvironmentVariablesString": "MallocSpaceEfficient=1 XPC_SERVICE_NAME=com.apple.wifivelocityd PATH=/usr/bin:/bin:/usr/sbin:/sbin XPC_FLAGS=0x0",
    "SourceProcessId": "569959646544105260",
    "SessionProcessId": "569959646544105260",
    "SubmittedByPid": "1108101562367",
    "SVUID": "0",
    "RGID": "0",
    "SourceThreadId": "0",
    "name": "ProcessRollup2MacV10",
    "RUID": "0",
    "CodeSigningFlags": "570506001",
    "ResponsiblePid": "18446744069414587103",
    "SigningId": "com.apple.ifconfig",
    "info": {
      "host": {
        "AgentTimeOffset": "1393432"
      }
    },
    "cid": ""
  },
  "process": {
    "args": [
      "/sbin/ifconfig",
      "-a",
      "-L",
      "-b",
      "-m",
      "-r",
      "-v"
    ],
    "parent": {
      "name": "wifivelocityd",
      "entity_id": "569959646544105260"
    },
    "pgid": 570594043738355460,
    "name": "ifconfig",
    "start": "2024-08-27T17:00:51.984Z",
    "pid": 63073,
    "args_count": 7,
    "entity_id": "570594043738355487",
    "command_line": "/sbin/ifconfig -a -L -b -m -r -v",
    "executable": "/sbin/ifconfig",
    "hash": {
      "sha256": "3b9718cd3d4a97fb368a5b0349d7e2c5e9d3d7fd858bfc86fafdb406f8a7b37c",
      "md5": "8091d8d700da16f59e771c7f83e211eb"
    }
  }
}
```

### Fixed Issues
N/A

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/)

### CODE REVIEW

**Comment by peterydzynski** [comment]
I am happy to provide an example log event have however it comes from Crowdstrike and has been fairly processed/modified. Let me know the best way to provide that if needed.

**Comment by nasbench** [comment]
> I am happy to provide an example log event have however it comes from Crowdstrike and has been fairly processed/modified. Let me know the best way to provide that if needed.

Hi @peterydzynski, you can link the example log in the PR body or just as a comment. I need for reviewing and documentation reasons. Even if its redacted, i need to see the Parent/Child to confirm.

Thanks in advance.

**Comment by peterydzynski** [comment]
I also realize I think i should have used `ParentImage` instead of `ParentProcessName` but I think this may be the parent process executable path not the name...

**Review by nasbench — APPROVED** [review]

**Comment by peterydzynski** [comment]
Thanks for the fix! Notes taken for next time!

**Pull request merged**
