### PR TITLE
Add Detection of RDP Session Reconnaissance Activity

### PR DESCRIPTION
**Pull request by ThureinOo**
### Summary of the Pull Request
This PR add a Detection of RDP Session Reconnaissance Activity via process_creation.

### Changelog
new: Detection of RDP Session Reconnaissance Activity

### Example Log Event
N/A

### Fixed Issues
N/A

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by nasbench** [comment]
Hey,

Thanks for the submission. Unfortunately, this is already covered in https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_eventlog_content_recon.yml

Closing as duplicate.

Cheers.

**Comment by ThureinOo** [comment]
Hi @nasbench,
Please let me know is there any way to search for the existing rules to avoid duplicates.

Thanks

**Comment by nasbench** [comment]
There isn't a "good" way to know for sure.

I'm pretty familiar with all the rules we have here so I know most of the stuff we cover.

You can use https://sigmasearchengine.com/ to search for strings from your rule and find matches.

You could also use https://www.nextron-systems.com/aurora/ in your LAB to check if there are any matches (just make sure you're using the latest release package)

Hope this helps.

**Comment by ThureinOo** [comment]
Thanks for your help @nasbench.

**Pull request closed without merging**
