### PR TITLE
Add `ipcidrv4` modifiers to manage CIDR

### PR DESCRIPTION
**Pull request by frack113**
HI,
My first try to make a modifiers `ipcidrv4`.

The rule 
```
title: Test ip range
description: test convert ip CIDR to string , detect nothing 
status: experimental
author: frack113
logsource:
    product: windows
    service: system
detection:
    selection:
        srcip|ipcidrv4:
            - 192.168.10.0/26
            - 10.10.0.0/16
            - 172.154.52.6/32
            - 'a string lol'
    condition: selection
falsepositives:
    - Unknown
level: critical
```
The output:
```
python sigmac -t es-qs -c .\config\winlogbeat.yml ..\test_ip.yml
srcip.keyword:(192.168.10.0 OR 192.168.10.1 OR 192.168.10.2 OR 192.168.10.3 OR 192.168.10.4 OR 192.168.10.5 OR 192.168.10.6 OR 192.168.10.7 OR 192.168.10.8 OR 192.168.10.9 OR 192.168.10.10 OR 192.168.10.11 OR 192.168.10.12 OR 192.168.10.13 OR 192.168.10.14 OR 192.168.10.15 OR 192.168.10.16 OR 192.168.10.17 OR 192.168.10.18 OR 192.168.10.19 OR 192.168.10.20 OR 192.168.10.21 OR 192.168.10.22 OR 192.168.10.23 OR 192.168.10.24 OR 192.168.10.25 OR 192.168.10.26 OR 192.168.10.27 OR 192.168.10.28 OR 192.168.10.29 OR 192.168.10.30 OR 192.168.10.31 OR 192.168.10.32 OR 192.168.10.33 OR 192.168.10.34 OR 192.168.10.35 OR 192.168.10.36 OR 192.168.10.37 OR 192.168.10.38 OR 192.168.10.39 OR 192.168.10.40 OR 192.168.10.41 OR 192.168.10.42 OR 192.168.10.43 OR 192.168.10.44 OR 192.168.10.45 OR 192.168.10.46 OR 192.168.10.47 OR 192.168.10.48 OR 192.168.10.49 OR 192.168.10.50 OR 192.168.10.51 OR 192.168.10.52 OR 192.168.10.53 OR 192.168.10.54 OR 192.168.10.55 OR 192.168.10.56 OR 192.168.10.57 OR 192.168.10.58 OR 192.168.10.59 OR 192.168.10.60 OR 192.168.10.61 OR 192.168.10.62 OR 192.168.10.63 OR 10.10.0.* OR 172.154.52.6 OR a\ string\ lol)
```
Please feel free to try, correct make better

### CODE REVIEW

**Review by StevenDias33 — APPROVED** [review]

**Comment by neu5ron** [comment]
may want to make an IP type - and pass via sigmac cli - for databases that differentiate between ip or string. For example, in Elastic there is an IP type, and although using how this function is now - would make easier to read - a lot of Elasticsearch mappings don't have string/keyword type for IP fields (ECS for exmaple).

this way we can leverage a lot of the different siem function's native ip support. so instead of, for example a /24, a 255 OR query.

although this will require a lot more siem specific backend configurations - and may make the rule "not applicable" to certain backends until they're added

**Comment by frack113** [comment]
There is no good solution for the monent : modifiers or backend ?
Maybe if I can put an option to change the behavior of my modifiers to the cli.
I have to think and works on it.

**Comment by Neo23x0** [comment]
I'd wait or check the new converter at https://github.com/SigmaHQ/sigmatools (private, but you should have access). 
@thomaspatzke may have some advise on that.

**Comment by thomaspatzke** [comment]
Modifiers can usually migrated 1:1 to the new code.

**Comment by frack113** [comment]
Hi,
a real headache for me, will probably wait to have a better level in python to attack such a big piece.
Yet the idea seemed simple at the beginning to me.

**Comment by frack113** [comment]
> 
> 
> I'd wait or check the new converter at https://github.com/SigmaHQ/sigmatools (private, but you should have access).
> @thomaspatzke may have some advise on that.

It's done, `SigmaCidrv4Expression` has been added

**Comment by thomaspatzke** [comment]
> Hi,
> a real headache for me, will probably wait to have a better level in python to attack such a big piece.
> Yet the idea seemed simple at the beginning to me.

Please don't hesitate to contribute anyways! Contributing is a great way to learn and your code is better than you think and definitely valuable! 👍

**Comment by frack113** [comment]
Hi,
Now how do I go from sigmatools to sigmac ?

**Comment by frack113** [comment]
Done in sigmatools

**Pull request closed without merging**
