### PR TITLE
Detect net use password plaintext

### PR DESCRIPTION
**Pull request by redsand**
round 2

### CODE REVIEW

**Comment by Neo23x0** [comment]
Please try to avoid regular expressions. They're very expensive in some backends.

**Comment by redsand** [comment]
> Please try to avoid regular expressions. They're very expensive in some backends.

Thanks for the feedback.  How would you write this detection without using regular expressions?

**Comment by redsand** [comment]
very nice! this will help me to think of it differently, much appreciated

**Comment by Neo23x0** [comment]
You regex is more exact and more solid. 
It's just that the performance impact of a regular expression is pretty high in some backends and other backends don't even support it. It's still possible that the two wildcard symbols in a single string can cause problems with some backends.

**Comment by redsand** [comment]
I have updated the rule to fix the issue per my above comment.  Please let me know if this is sufficient.

**Pull request merged**
