### PR TITLE
FP: System image (driver) restoring files. Valid behavior

### PR DESCRIPTION
**Pull request by redsand**
Example
```
2022-05-24 22:24:44  REDACTED Sysmon: 11: File created | RuleName=- | UtcTime=2022-05-24 22:24:44.403 | ProcessGuid={f4b6f253-acc4-627d-0100-000000007501} | ProcessId=4 | Image=System | TargetFilename=D:\inetpub\wwwroot\LenderCompliance\Forms\CovenantCalculationCtrlForm.aspx | CreationUtcTime=2022-05-19 20:24:51.262 | pid=1984 | level=0 | sys_version=2 | category=File created (rule: FileCreate) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=5028660 | app="C:\Windows\sysmon64.exe" | tid=4956 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | type=notice(4) 
```

### CODE REVIEW

**Comment by frack113** [comment]
Hello,
I think it is a `or not Image: 'System`.
```yaml
  false_positives:    # false positives when unpacking some executables in $TEMP
    - TargetFilename|contains:
      - '\AppData\Local\Temp\'
      - '\Windows\Temp\'
    - Image: 'System' # fp : backup/restore from drivers
```
Give
```bash
PS D:\rootme\sigma\tools> python sigmac -t splunk -c .\config\generic\sysmon.yml D:\rootme\test_rule.yml
(EventID="11" ((((TargetFilename="*\\inetpub\\wwwroot\\*" (TargetFilename="*.asp*" OR TargetFilename="*.ashx*" OR TargetFilename="*.ph*")) NOT ((TargetFilename="*\\AppData\\Local\\Temp\\*" OR TargetFilename="*\\Windows\\Temp\\*") OR Image="System")) OR (((TargetFilename="*\\www\\*" OR TargetFilename="*\\htdocs\\*" OR TargetFilename="*\\html\\*") TargetFilename="*.ph*") NOT ((TargetFilename="*\\AppData\\Local\\Temp\\*" OR TargetFilename="*\\Windows\\Temp\\*") OR Image="System"))) OR ((TargetFilename="*.jsp" OR (TargetFilename="*\\cgi-bin\\*" TargetFilename="*.pl*")) NOT ((TargetFilename="*\\AppData\\Local\\Temp\\*" OR TargetFilename="*\\Windows\\Temp\\*") OR Image="System"))))
```
with `condition: (selection_2 and selection_3) or (selection_4 and selection_5) or (selection_6) and not false_positives`
```bash
PS D:\rootme\sigma\tools> python sigmac -t splunk -c .\config\generic\sysmon.yml D:\rootme\test_rule.yml
(EventID="11" (((TargetFilename="*\\inetpub\\wwwroot\\*" (TargetFilename="*.asp*" OR TargetFilename="*.ashx*" OR TargetFilename="*.ph*")) OR ((TargetFilename="*\\www\\*" OR TargetFilename="*\\htdocs\\*" OR TargetFilename="*\\html\\*") TargetFilename="*.ph*")) OR ((TargetFilename="*.jsp" OR (TargetFilename="*\\cgi-bin\\*" TargetFilename="*.pl*")) NOT ((TargetFilename="*\\AppData\\Local\\Temp\\*" OR TargetFilename="*\\Windows\\Temp\\*") OR Image="System"))))
```

**Comment by frack113** [comment]
When I read your filter without backend eye I get  
`I don't want { (TargetFilename '\AppData\Local\Temp\ OR '\Windows\Temp\') AND Image 'System' }`
Your log is 
```
TargetFilename=D:\inetpub\wwwroot\LenderCompliance\Forms\CovenantCalculationCtrlForm.aspx
Image=System
```
So will not be filter
Convert with splunk give the same logic
```
PS D:\rootme\sigma\tools> python sigmac -t splunk -c .\config\generic\sysmon.yml D:\rootme\test_rule.yml
(EventID="11" 
  (
    (
      ((TargetFilename="*\\inetpub\\wwwroot\\*" (TargetFilename="*.asp*" OR TargetFilename="*.ashx*" OR TargetFilename="*.ph*")) NOT ((TargetFilename="*\\AppData\\Local\\Temp\\*" OR TargetFilename="*\\Windows\\Temp\\*") Image="System"))
      OR (((TargetFilename="*\\www\\*" OR TargetFilename="*\\htdocs\\*" OR TargetFilename="*\\html\\*") TargetFilename="*.ph*") NOT ((TargetFilename="*\\AppData\\Local\\Temp\\*" OR TargetFilename="*\\Windows\\Temp\\*") Image="System"))
    )
    OR ((TargetFilename="*.jsp" OR (TargetFilename="*\\cgi-bin\\*" TargetFilename="*.pl*")) NOT ((TargetFilename="*\\AppData\\Local\\Temp\\*" OR TargetFilename="*\\Windows\\Temp\\*") Image="System"))
  )
)
```

**Comment by redsand** [comment]
Updated and split out to separate false positive checks

**Comment by redsand** [comment]
@frack113 any additional updates needed for this item?

**Comment by frack113** [comment]
Should do the works.
I really think we need to split the rule because the 'condition' becomes really hard to read at first.

**Comment by redsand** [comment]
> Should do the works. I really think we need to split the rule because the 'condition' becomes really hard to read at first.

I absolutely agree with this.  Since it wasn't my rule originally, I quickly became confused on what exactly it was trying to match against, due to the complexity

**Pull request merged**
