### PR TITLE
Update proc_creation_win_cmd_delete.yml

### PR DESCRIPTION
**Pull request by veramine**
Remove false positive of explorer.exe executing:  	"CommandLine": "\"C:\\Windows\\System32\\cmd.exe\" /q /c rmdir /s /q \"C:\\Users\\user\\AppData\\Local\\Microsoft\\OneDrive\\22.227.1030.0001\"",

### CODE REVIEW

**Comment by nasbench** [comment]
Can you give a bit more context on how this FP got generated? Cause it seems like some sort of a script.

**Comment by nasbench** [comment]
Any updates @veramine ?

**Comment by veramine** [comment]
I think it was some kind of Windows 10 OneDrive auto-update or cleanup script.  Here was the sequence of three commands run at Medium IL by the logged in user.  My guess is AT / Scheduled Task but I haven't gone to look more closely.

```
"C:\Windows\System32\cmd.exe" /q /c del /q "C:\Users\admin\AppData\Local\Microsoft\OneDrive\Update\OneDriveSetup.exe"

"C:\Windows\System32\cmd.exe" /q /c del /q "C:\Users\admin\AppData\Local\Microsoft\OneDrive\StandaloneUpdater\OneDriveSetup.exe"

"C:\Windows\System32\cmd.exe" /q /c rmdir /s /q "C:\Users\admin\AppData\Local\Microsoft\OneDrive\22.227.1030.0001"
```

**Comment by nasbench** [comment]
> I think it was some kind of Windows 10 OneDrive auto-update or cleanup script. Here was the sequence of three commands run at Medium IL by the logged in user. My guess is AT / Scheduled Task but I haven't gone to look more closely.
> 
> ```
> "C:\Windows\System32\cmd.exe" /q /c del /q "C:\Users\admin\AppData\Local\Microsoft\OneDrive\Update\OneDriveSetup.exe"
> 
> "C:\Windows\System32\cmd.exe" /q /c del /q "C:\Users\admin\AppData\Local\Microsoft\OneDrive\StandaloneUpdater\OneDriveSetup.exe"
> 
> "C:\Windows\System32\cmd.exe" /q /c rmdir /s /q "C:\Users\admin\AppData\Local\Microsoft\OneDrive\22.227.1030.0001"
> ```

I have an issue with the parent being `explorer`. If it's a scheduled task the parent should be different. Can you please double-check?

**Pull request closed without merging**
