### PR TITLE
Create sysmon_svchost_cred_dump.yml

### PR DESCRIPTION
**Pull request by luffynextgen**
Rule to detect when credentials are dump from svchost through a soft, as mimikatz or reviewed by a soft such as process hacker

### CODE REVIEW

**Comment by frack113** [comment]
Hello,
Can you fix the category to `process_access` and then remove `EventID: 10` not usefull.
sysmon is a `service` , use config/generic/sysmon.yml for the EventID mapping with sigmac.

`destination_process_name` is  `TargetImage` in sysmon event
`source_process_name` is `SourceImage` in sysmon event

Thanks

**Comment by luffynextgen** [comment]
Hello,

I fixed it accordingly to your return.

Kind regards

**Comment by frack113** [comment]
`python sigmac -t es-qs -c .\config\generic\sysmon.yml d:\FrackSigma\sysmon_svchost_cred_dump.yml`
get 
`(EventID:"10" AND (TargetImage:"svchost.exe" AND GrantedAccess:"0x143a") AND (NOT (SourceImage:("services.exe" OR "msiexec.exe"))))`
So seem all good

**Review by StevenDias33 — APPROVED** [review]

**Comment by frack113** [comment]
Sorry,
to succeed the workflow :

- tag are lowercase `- attack.t1548`
- for the title `title: SVCHOST Credential Dump`

**Comment by Neo23x0** [comment]
I fixed the missing `id` field, added `|endswith` to the field selectors and `*\' to the values.

**Pull request merged**
