### PR TITLE
Permissions granted over a Cloud Service Account

### PR DESCRIPTION
**Pull request by TheEis4Extra**
### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by ThomasTheTech** [comment]
> 

> ### Summary of the Pull Request

> 

> ### Detailed Description of the Pull Request / Additional Comments

> 

> ### Example Log Event

> 

> ### Fixed Issues

> 

> ### SigmaHQ Rule Creation Conventions

> - If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

**Comment by ThomasTheTech** [comment]
### Summary of the Pull Request



### Detailed Description of the Pull Request / Additional Comments



### Example Log Event



### Fixed Issues



### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

**Comment by nasbench** [comment]
This will require some work. As the old "gcp" rules used a convention of `gcp.audit` to call the fields of the `protoPayload`

So for example you used `protoPayload.methodName` while in older rules it's `gcp.audit.method_name`.

I have zero knowledge in GCP logs so I can't say. I would either follow the same convention or change every rule.

If you could provide an example log that would be much appreciated :)

**Comment by nasbench** [comment]
Closing this as inactive for now :)

Feel free to open it again.

**Pull request closed without merging**
