### PR TITLE
update application uninstalled rule

### PR DESCRIPTION
**Pull request by YamatoSecurity**
Some English fixes. Also, the alert level should probably be informational instead of low?
This event can be quite noisy in my experience.

### CODE REVIEW

**Comment by frack113** [comment]
Thanks for the English fixes.

for the [level](https://github.com/SigmaHQ/sigma/wiki/Specification#level)
`low` should not be use for daily detection, there are `Notable event but rarely an incident` .

You can run it periodically to see if there are any changes in the results.
Or make a custom one with the security software installed on your park.

Low rule are not a 1 vs 1 match , it's more of a clue to find a suspicious behavior (often it's windows itself or a bad admin script)

**Comment by frack113** [comment]
@YamatoSecurity what do you feel about my answer ?

**Comment by YamatoSecurity** [comment]
Sorry for the late response and thank you for the reply!
I see. As low level alerts are defined as a type of event of interest then it is probably ok as a low level alert. Although as there are so many alerts, I have some doubts on whether it is possible for an analyst to review them all manually at scale.

**Comment by frack113** [comment]
I agree, that's why I don't use it in production.
It is necessary to master the software park to know what can be important when there is an update session.

You can use the TOP and  LESS 10 to sort the result and have quick view.

Should be fine to add a warning that the rule can be very verbose and need to be tune in the description.
What do think ?

**Pull request merged**
