### PR TITLE
Add new rules for detection msdt.exe create file to autorun

### PR DESCRIPTION
**Pull request by r00tik**
detecting the creation of a file in the startup folder by the process msdt.exe

### CODE REVIEW

**Comment by Neo23x0** [comment]
This rule has several issues that'll show up, once I approve and run the workflow. 

It's detection idea is good, but it's too specific. There are many more folders in which a file creation by msdt.exe could be suspicious.

**Comment by Neo23x0** [comment]
I've fixed the issues with the rule myself

**Comment by r00tik** [comment]
@Neo23x0 Do I need to do something?

**Comment by Neo23x0** [comment]
No, just wait until the tests are completed

**Pull request merged**
