### PR TITLE
rule: missing space characters

### PR DESCRIPTION
**Pull request by Neo23x0**
https://twitter.com/cyb3rops/status/1562072617552678912

### CODE REVIEW

**Comment by nasbench** [comment]
I would also add one with the double quote `- '"cmd/c'` in selection1

**Comment by frack113** [comment]
> I would also add one with the double quote `- '"cmd/c'` in selection1

Can not be  `'cmd/c'` to cover \ and " ?

**Comment by Neo23x0** [comment]
It would be a bit to prone to FPs, I guess, e.g. 

```
someprog.exe -url http://domain.com/webcmd/command/1/upoad 
```

**Comment by Neo23x0** [comment]
But I think I should add the "/k" flag as well 
e.g.
```
cmd.exe/kcmd/kwhoami/priv
```

**Pull request merged**
