### PR TITLE
Create ala-suricata.yml

### PR DESCRIPTION
**Pull request by heyibrahimkhan**
Suricata logs mapping for Azure Log Analytics added

### CODE REVIEW

**Comment by frack113** [comment]
Hello,
Are you sure of `parse_json(RawData).` seen pretty bad parsing.
It should be more like `eve` or `suricata`

**Comment by heyibrahimkhan** [comment]
> 
> 
> Hello,
> Are you sure of `parse_json(RawData).` seen pretty bad parsing.
> It should be more like `eve` or `suricata`

Hi @frack113 

Yep. That's because Suricata log fields when integrated with Azure Sentinel by default appear in a not so detection friendly format.

In order to compensate for that, parse_json type items have to be used otherwise detections are rendered useless.

Hope this helps clarify any issues.

Open to better suggestions.

**Comment by heyibrahimkhan** [comment]
++ @w0rk3r @0xtf

**Comment by frack113** [comment]
Thanks for the information.

**Pull request merged**
