### PR TITLE
Create proc_creation_win_rundll32_ext_drive.yml

### PR DESCRIPTION
**Pull request by angelovioletti**
### Summary of the Pull Request

New rule for detecting the execution of rundll32.exe processes where the current directory is an external drive, based on the analysis of a BumbleBee sample.

### Detailed Description of the Pull Request / Additional Comments

This rule detects the execution of rundll32.exe processes where the current directory is an external drive. This technique is commonly abused by malware to deliver the payload through ISO files that are mounted on the system. When executed, the rundll32.exe process loads the payload from the external drive and therefore the current directory is an external one.

### Example Log Event

False positives can arise when the root system drive is not C.

### Fixed Issues

NA

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by nasbench** [comment]
Hi, and thanks for your contribution.

Unfortunately the logic described in this rule is already covered by [proc_creation_win_lolbin_not_from_c_drive.yml](https://github.com/SigmaHQ/sigma/blob/2710bf4710f21ad42ddbc0caa82ed0b2bf2ae3f2/rules/windows/process_creation/proc_creation_win_lolbin_not_from_c_drive.yml#L8)

**Comment by angelovioletti** [comment]
> Hi, and thanks for your contribution.
> 
> Unfortunately the logic described in this rule is already covered by [proc_creation_win_lolbin_not_from_c_drive.yml](https://github.com/SigmaHQ/sigma/blob/2710bf4710f21ad42ddbc0caa82ed0b2bf2ae3f2/rules/windows/process_creation/proc_creation_win_lolbin_not_from_c_drive.yml#L8)

Hey, thanks a lot for your reply.
The rule is not completely covered by the one you've mentioned because I'm checking for the value OriginalFileName instead of Image. I'm doing this since some malwares, eg BumbleBee copies and renames rundll32.exe and therefore they evade that Sigma rule.
The explanation is in this blog post: https://sec-consult.com/blog/detail/bumblebee-hunting-with-a-velociraptor/

**Comment by nasbench** [comment]
Hum, I didn't notice the OFN usage.

It was in the plan to add OFN to that rule. You can do it in this PR then and delete your rule.

```yml
selection:
        - Image|endswith:
            - '\rundll32.exe'
            - '\calc.exe'
            - '\mshta.exe'
            - '\cscript.exe'
            - '\wscript.exe'
            - '\regsvr32.exe'
            - '\installutil.exe'
            - '\cmstp.exe'
        - OriginalFileName:
            - 'RUNDLL32.EXE'
            - 'CALC.EXE'
            - 'MSHTA.EXE'
            - 'cscript.exe'
            - 'wscript.exe'
            - 'REGSVR32.EXE'
            - 'installutil.exe'
            - 'CMSTP.EXE'
```

**Comment by angelovioletti** [comment]
> Hum, I didn't notice the OFN usage.
> 
> It was in the plan to add OFN to that rule. You can do it in this PR then and delete your rule.
> 
> ```yaml
> selection:
>         - Image|endswith:
>             - '\rundll32.exe'
>             - '\calc.exe'
>             - '\mshta.exe'
>             - '\cscript.exe'
>             - '\wscript.exe'
>             - '\regsvr32.exe'
>             - '\installutil.exe'
>             - '\cmstp.exe'
>         - OriginalFileName:
>             - 'RUNDLL32.EXE'
>             - 'CALC.EXE'
>             - 'MSHTA.EXE'
>             - 'cscript.exe'
>             - 'wscript.exe'
>             - 'REGSVR32.EXE'
>             - 'installutil.exe'
>             - 'CMSTP.EXE'
> ```

Cool, thanks for the feedback.

**Review by nasbench — APPROVED** [review]

**Comment by nasbench** [comment]
Thanks for the contribution @angelovioletti Much appreciated

**Comment by nasbench** [comment]
cc @phantinuss

**Review by phantinuss — APPROVED** [review]

**Comment by phantinuss** [comment]
sry, must have missed this PR.

**Pull request merged**
