### PR TITLE
Auditd rule - Systemd Service Creation

### PR DESCRIPTION
**Pull request by zakibro**

### CODE REVIEW

**Comment by frack113** [comment]
```yaml
    name: 
         - '/usr/lib/systemd/system/*'
         - '*/.config/systemd/user/*'
         - '/etc/systemd/system/*'
```
will be convert to ` */usr..* OR */.config..* OR */etc...*`
I think you want
```
  path:
    type: 'PATH'
    nametype: 'CREATE'
  nane_1:
    name|startswith: 
         - '/usr/lib/systemd/system/'
         - '/etc/systemd/system/'
  name_2:
    name|contains:
         - '/.config/systemd/user/'
  condition: path and 1 of name_*
```
will be convert to `(path part) AND (/usr..* OR /etc...* OR */.config..*) `

**Comment by frack113** [comment]
Hi,
With [auditd Neo23x0 conf](https://github.com/Neo23x0/auditd) and [atomic-operator](https://github.com/swimlane/atomic-operator)
I get
 `type=PATH msg=audit(1644048735.298:29868): item=1 name="/etc/systemd/system/art-systemd-service.service" inode=1191871 dev=08:04 mode=0100644 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0`
I did not succed to have nametype `CREATE`
Do you have a special line for auditd conf ? 
Can be add logsource/definition to help

**Comment by zakibro** [comment]
I have the same config.

You can see me testing it there: https://youtu.be/CoJxn-_G3PM

Around 40min-ish

**Comment by frack113** [comment]
Thanks,
I h--e auditd

**Pull request merged**
