### PR TITLE
new rules

### PR DESCRIPTION
**Pull request by sreemanshanker**

### CODE REVIEW

**Comment by Neo23x0** [comment]
First, thanks for the pull request. 

Could you please split up such big pull request into smaller ones. They are easier to process on our side.

**Comment by Neo23x0** [comment]
Also: please check the file naming convention in the existing directories.
You rule files have completely uncommon names.

**Comment by sreemanshanker** [comment]
> First, thanks for the pull request.
> 
> Could you please split up such big pull request into smaller ones. They are easier to process on our side.

Hi !
Just saw this. will do so. I think its big cause it has been queuing for some time :)

**Comment by sreemanshanker** [comment]
have renamed and redone as per request.

**Comment by frack113** [comment]
Hi,
start working on it, https://github.com/frack113/sigma/tree/fix_PR_617 many works to do before PR...

**Comment by sreemanshanker** [comment]
> Hi,
> start working on it,I only fix the structure to pass the test.
> 
> * [x]  rules/windows/builtin/Suspicious werfault.exe network connection outbound.yml -> win_suspicious_werfault_connection_outbound.yml
> * [x]  rules/windows/builtin/lolbas_execution_of_wuauclt.exe -> win_lolbas_execution_of_wuauclt.yml
> * [x]  rules/windows/process_creation/ASR bypass via AppVLP -> win_asr_bypass_via_appvlp_re.yml
> * [x]  rules/windows/process_creation/Arbitrary_Shell_Execution_via _settingcontent-Ms -> win_arbitrary_shell_execution_via_settingcontent.yml
> * [x]  rules/windows/process_creation/Credential access via password filter -> win_credential_access_via_password_filter.yml
> * [x]  rules/windows/process_creation/Detecting fake instances of hxtsr.exe -> win_detecting_fake_instances_of_hxtsr.yml
> * [x]  rules/windows/process_creation/Hiding malware in Fonts folder -> win_hiding_malware_in_fonts_folder.yml
> * [x]  rules/windows/process_creation/LOLbin execution via winget -> win_lolbin_execution_via_winget.yml
> * [x]  rules/windows/process_creation/Monitoring for persistence via BITS -> win_monitoring_for_persistence_via_bits.yml
> * [x]  rules/windows/process_creation/Write protect for storage disabled -> win_write_protect_for_storage_disabled.yml
> * [x]  rules/windows/process_creation/sticky-keys unauthenticated, privileged console access -> win_sticky_keys_unauthenticated_privileged_console_access.yml
> * [x]  rules/process_creation/win_Modification_of_existing _services_for_persistence_via commandline -> win_modif_of_services_for_via_commandline.yml
> * [x]  rules/windows/sysmon/Abusing Windows Telemetry For Persistence -> sysmon_abusing_windows_telemetry_for_persistence.yml
> 
> https://github.com/frack113/sigma/tree/PR_617_V2
> Use it or I can make a PR , as you wish

go for it. just make a PR. thanks btw !

**Comment by frack113** [comment]
Hi , 
As it merge , you can close it.
Thanks

**Pull request closed without merging**
