### PR TITLE
Adding detection for use of MS Teams execution, false positives unknown

### PR DESCRIPTION
**Pull request by redsand**
New detection per:

https://twitter.com/misconfig/status/1481198346379436035

### CODE REVIEW

**Comment by Neo23x0** [comment]
This should be covered by the Squirrel LOLBIN rule

https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/win_susp_squirrel_lolbin.yml

PS: I noticed that the filter in that rule is currently dysfunctional and fixed it in another commit

**Comment by redsand** [comment]
oh wow, great catch!  My grep's failed me! i was grep'ing for the word "team".  lmk if u want me to zap this pr

**Comment by redsand** [comment]
closing pull request, as behavior is covered by https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/win_susp_squirrel_lolbin.yml

**Comment by Neo23x0** [comment]
Nevertheless, thanks for the effort and rule

**Pull request closed without merging**
