### PR TITLE
Rule Add User To Root Rroup

### PR DESCRIPTION
**Pull request by tuanhxh1**
Detects add user to root group in linux using usermod

### CODE REVIEW

**Comment by Neo23x0** [comment]
This pull request would modify the ALA backend

**Comment by nasbench** [comment]
Ping @tuanhxh1 any updates about this PR. What were you trying to fix?

**Comment by tuanhxh1** [comment]
Description have two "add user" string. Can you fix this.

**Comment by nasbench** [comment]
> Description have two "add user" string. Can you fix this.

The description doesn't match your commit. You had a PR that created a rule related to `usermord` here https://github.com/SigmaHQ/sigma/pull/2801

I just want to know what your fix to the ALA backend do? Can you elaborate? 

If it's just a mistake I can close this PR

**Comment by tuanhxh1** [comment]
I think it's just a mistake and you can close this PR :))

**Comment by nasbench** [comment]
> I think it's just a mistake and you can close this PR :))

Alright. Thanks for the quick reply @tuanhxh1 and for your contribution :)

Cheers.

**Pull request closed without merging**
