### PR TITLE
Update rule PowerShell RDP Port

### PR DESCRIPTION
**Pull request by tuanhxh1**
### Example Log Event
Pipeline execution details for command line: Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber". 

Context Information: 
	DetailSequence=1
	DetailTotal=1

	SequenceNumber=29

	UserId=BLUE\Administrator
	HostName=ConsoleHost
	HostVersion=5.1.14393.1884
	HostId=b02ff59f-0cc9-4b4c-b061-1915534a50d0
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
	EngineVersion=5.1.14393.1884
	RunspaceId=06735886-4e13-42a7-a5c7-1db88558591f
	PipelineId=10
	ScriptName=
	CommandLine=Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber" 

Details: 
CommandInvocation(Get-ItemProperty): "Get-ItemProperty"
ParameterBinding(Get-ItemProperty): name="Path"; value="HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp"
ParameterBinding(Get-ItemProperty): name="Name"; value="PortNumber"

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by nasbench** [comment]
How is checking the port number suspicious on it's own?

**Comment by tuanhxh1** [comment]
@nasbench The purpose of detect RDP port has been changed. Example: The attacker can get the new port information to conduct a rescan

**Comment by frack113** [comment]
@tuanhxh1  `Get-ItemProperty` is to display the port.
Your title and description don't go together.

**Comment by nasbench** [comment]
@tuanhxh1 the rule logic isn't suited for what you're trying to detect. If you're trying to detect a change of the port then you could either use a registry event, which is already covered by this rule https://github.com/SigmaHQ/sigma/blob/44d9d9ee0e034cb456e5ba60896929891b8eba8e/rules/windows/registry/registry_set/registry_set_change_rdp_port.yml#L19-L24 or you could use a process_creation/powershell event to detect the change. which is covered by reg usage here (but not in powershell. You could add it) https://github.com/SigmaHQ/sigma/blob/44d9d9ee0e034cb456e5ba60896929891b8eba8e/rules/windows/process_creation/proc_creation_win_reg_rdp_keys_tamper.yml#L18-L45

If you wanna keep the logic of the query/recon. On it's own then

- update the titles and description to reflect this
- reduce the level to low as on its own it can't amount to a medium rule
- add public reference of real world usage if possible

**Comment by nasbench** [comment]
@tuanhxh1 any update on this?

**Comment by nasbench** [comment]
Closing this as inactive for now. Feel free to open again if you have update :)

**Pull request closed without merging**
