### PR TITLE
Update winlogbeat-modules-enabled.yml

### PR DESCRIPTION
**Pull request by leegengyu**
Update mapping for `EventID` and `TargetObject`.

Reference for `event.code` and `registry.path`: https://www.elastic.co/guide/en/beats/winlogbeat/current/exported-fields-ecs.html

### CODE REVIEW

**Review by frack113 — APPROVED** [review]

**Comment by leegengyu** [comment]
Updated 1 more mapping for `ServiceName` (same reference link as above).

**Comment by neu5ron** [comment]
should keep eventid as winlog.event_id

**Comment by leegengyu** [comment]
@neu5ron Hey there,

Could you explain your rationale please? Thanks!

**Comment by neu5ron** [comment]
@leegengyu
👋 
mainly consistency across ECS versions. What I have noticed with event.code:
- went from integer to keyword
- did not always exist

**Comment by neu5ron** [comment]
well, event.id is officially gone. so good call on using event.code ;)


my magic 8 ball says - bummer

**Comment by leegengyu** [comment]
> well, event.id is officially gone. so good call on using event.code ;)
> 
> my magic 8 ball says - bummer to all previous data

May I ask where did you see that `event.id` is officially gone?

Thanks!

**Pull request merged**
