### PR TITLE
Permissions granted over a Cloud Service Account rule added

### PR DESCRIPTION
**Pull request by ThomasTheTech**
### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by ThomasTheTech** [comment]
Hey nasbench. I filled out the template this time. Is it not coming through. Sorry things my first pull request.

**Comment by nasbench** [comment]
> Hey nasbench. I filled out the template this time. Is it not coming through. Sorry things my first pull request.

Hi Thomas, It's still empty values from my side. A short description of the intent and any logs you could provide would be much appreciated.

Also the notation of the field `protoPayload. service data.policyDelta.bindingDeltas[*].role` is weird for me by having a wildcard in it. Can you provide an example so that I can suggest how would you translate it in SIGMA?

Cheers.

**Comment by nasbench** [comment]
You can put it here in the comment no worries.

**Comment by ThomasTheTech** [comment]
Going to start over from scratch

**Pull request closed without merging**
