### PR TITLE
Updated sysmon config and rewrite rules to use categories

### PR DESCRIPTION
**Pull request by stevengoossensB**
- Updated sysmon config to have categories for other EventIDs
- Updated rules to include categories instead of explicit EventIDs

### CODE REVIEW

**Comment by Neo23x0** [comment]
When using a "category", you have to remove the "service: sysmon", since the rule has become a generic rule.

**Comment by stevengoossensB** [comment]
Ok, let me fix that.

**Comment by Neo23x0** [comment]
Why haven't we merged this already?

**Comment by Neo23x0** [comment]
Ah, you made changes 5 days ago

**Pull request merged**
