### PR TITLE
Modified dates automatically changed if last commit date is > 3 days …

### PR DESCRIPTION
**Pull request by elhoim**
…diff with modified date in file.\n Corner cases not handled: commit that are superficial changes (renames, file move, metadata adjustment, etc...).

If wanted/needed i can try to add corner cases handling in the script that generates this, but i would like a list of corner cases.

### CODE REVIEW

**Comment by Neo23x0** [comment]
> Corner cases not handled: commit that are superficial changes (renames, file move, metadata adjustment, etc...).
>
> If wanted/needed ...

Absolutely. We often change just the indentation or fix a typo in the description. In these cases we do NOT want the modification date to change. 

See https://github.com/SigmaHQ/sigma/wiki/Rule-Creation-Guide#date for the list of fields/sections in which changes lead to a change of the modified date.

**Comment by frack113** [comment]
When I review a rule I check if modified have been update when needed.
Many rules have been change  but not the detection part.

**Comment by frack113** [comment]
We can close it.

**Comment by elhoim** [comment]
Will try to improve my script

**Pull request closed without merging**
