### PR TITLE
Allow dsac, wmi and mssql sqlps.exe to perform powershell execution over named pipes

### PR DESCRIPTION
**Pull request by redsand**
DSAC - Active Directory Admin Client

Example :

```
2022-01-18 19:23:43 device-01.domainname.co Sysmon: 17: Pipe Created | RuleName=- | EventType=CreatePipe | UtcTime=2022-01-18 19:23:43.838 | ProcessGuid={B7C4C965-13BC-61E7-2A0D-000000006E00} | ProcessId=6300 | PipeName=\PSHost.132870074208708397.6100.DefaultAppDomain.dsac | Image=C:\Windows\system32\dsac.exe | pid=2604 | level=0 | sys_version=1 | category=Pipe Created (rule: PipeEvent) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=447383191 | app="C:\Windows\sysmon64.exe" | tid=5716 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | type=notice(4) 
```

### CODE REVIEW

**Comment by redsand** [comment]
Additional FP Example for wmi:

```
2022-01-18 21:15:45 device-01.domain.com Sysmon: 17: Pipe Created | RuleName=- | EventType=CreatePipe | UtcTime=2022-01-18 21:15:45.250 | ProcessGuid={C537D2AE-2DFF-61E7-EB1E-000000005800} | ProcessId=5844 | PipeName=\PSHost.132870141435889601.5844.DscPsPluginWkr_AppDomain.WmiPrvSE | Image=C:\Windows\system32\wbem\wmiprvse.exe | pid=2148 | level=0 | sys_version=1 | category=Pipe Created (rule: PipeEvent) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=4831020 | app="C:\Windows\sysmon64.exe" | tid=3908 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | type=notice(4) 
```

**Comment by redsand** [comment]
Adding support for MsSQL sqlps.exe

**Comment by redsand** [comment]
```
2022-01-18 09:00:03 device-01.domainname.co Sysmon: 17: Pipe Created | RuleName=- | EventType=CreatePipe | UtcTime=2022-01-18 09:00:03.042 | ProcessGuid={1C538E9F-8190-61E6-97BD-00000000EF00} | ProcessId=11908 | PipeName=\PSHost.132869700005761276.11908.DefaultAppDomain.SQLPS | Image=C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\SQLPS.exe | pid=2220 | level=0 | sys_version=1 | category=Pipe Created (rule: PipeEvent) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=29548907 | app="C:\Windows\sysmon64.exe" | tid=5276 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | type=notice(4)
```

**Comment by frack113** [comment]
> ```
> 2022-01-18 09:00:03 device-01.domainname.co Sysmon: 17: Pipe Created | RuleName=- | EventType=CreatePipe | UtcTime=2022-01-18 09:00:03.042 | ProcessGuid={1C538E9F-8190-61E6-97BD-00000000EF00} | ProcessId=11908 | PipeName=\PSHost.132869700005761276.11908.DefaultAppDomain.SQLPS | Image=C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\SQLPS.exe | pid=2220 | level=0 | sys_version=1 | category=Pipe Created (rule: PipeEvent) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=29548907 | app="C:\Windows\sysmon64.exe" | tid=5276 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | type=notice(4)
> ```

What do you think of add a `filter3` 
```
filter3:
  Image|contains|all:
    - ':\Program Files'
    - '\Microsoft SQL Server\'
  Image|endswith: '\Tools\Binn\SQLPS.exe'
``

**Comment by redsand** [comment]
> > ```
> > 2022-01-18 09:00:03 device-01.domainname.co Sysmon: 17: Pipe Created | RuleName=- | EventType=CreatePipe | UtcTime=2022-01-18 09:00:03.042 | ProcessGuid={1C538E9F-8190-61E6-97BD-00000000EF00} | ProcessId=11908 | PipeName=\PSHost.132869700005761276.11908.DefaultAppDomain.SQLPS | Image=C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\SQLPS.exe | pid=2220 | level=0 | sys_version=1 | category=Pipe Created (rule: PipeEvent) | op=Info | Microsoft-Windows-Sysmon/Operational=true | key=0x8000000000000000 | id=29548907 | app="C:\Windows\sysmon64.exe" | tid=5276 | channel="Microsoft-Windows-Sysmon/Operational" | pid_user="NT AUTHORITY\SYSTEM" | sid=S-1-5-18 | account type=User | type=notice(4)
> > ```
> 
> What do you think of add a `filter3`
> 
> ```
> filter3:
>   Image|contains|all:
>     - ':\Program Files'
>     - '\Microsoft SQL Server\'
>   Image|endswith: '\Tools\Binn\SQLPS.exe'
> ```

This has been updated

**Comment by redsand** [comment]
looks like @Neo23x0 included some new tests that are breaking a lot of yaml files?  What should I do?

**Pull request merged**
