### PR TITLE
Create azure_priviledged_role_assignment_add.yml

### PR DESCRIPTION
**Pull request by MarkMorow**
User added to privilege role assignment

### CODE REVIEW

**Comment by frack113** [comment]
Hi,
From the ref
```
Category = Role Management
-and-
Activity Type – Add eligible member (permanent)
-and-
Activity Type – Add eligible member (eligible)
-and-
Status = Success/failure
-and-
Modified properties = Role.DisplayName
```
so more like (Caution I don't know the correct field name)
```yaml
    selection:
        Category: Role Management   # Or it is allready in service: auditlogs ?
        properties.message|contains|all:  # As it is an and 
            - Add eligible member (permanent)
            - Add eligible member (eligible)
        Status: 
            - Success
            - failure
        Modified properties: Role.DisplayName # I think it should be like "modified.properties" 
    condition: selection
```

**Comment by MarkMorow** [comment]
@frack113 Let me double check I believe it's an OR. @Yochana-H  do you remember? The log is in the Azure AD Audit logs.

**Comment by MarkMorow** [comment]
@frack113  confirmed it's an OR. We'll update the docs.microsoft.com. Do we need anything else on this rule?

**Comment by frack113** [comment]
Ok thanks

**Pull request merged**
