### PR TITLE
Update Rule Remove Package

### PR DESCRIPTION
**Pull request by tuanhxh1**
### Summary of the Pull Request

This PR adds a new linux rule related to package removal

### Detailed Description of the Pull Request / Additional Comments

N/A

### Example Log Event

N/A

### Fixed Issues

N/A

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by nasbench** [comment]
Hi and thanks for your contribution.

I went ahead and made some updates that add more variants that are available on the systems such as `apt`, `rpm` and `dpkg`. I also updated the metadata such as the `title` and `description` to fit with the SIGMA rule base.

Thanks.

**Review by nasbench — APPROVED** [review]

**Comment by nasbench** [comment]
@tuanhxh1 as a side note. When you open a PR please make sure to follow the template by filling in the necessary details. Failing to do so will make it harder for us to review your PR.

**Comment by tuanhxh1** [comment]
@nasbench Thanks for support :)

**Comment by nasbench** [comment]
> @nasbench Thanks for support :)

No worries. Thanks again for your contribution :)

**Pull request merged**
