### PR TITLE
Added rule for default cobalt strike certificate

### PR DESCRIPTION
**Pull request by d4rk-d4nph3**
Remark: I have replaced the dot in the fields to underscore.

Screen Shot 2021-06-23 at 10 19 22

### Log:
```#fields	ts	id	certificate.version	certificate.serial	certificate.subject	certificate.issuer	certificate.not_valid_before	certificate.not_valid_after	certificate.key_alg	certificate.sig_alg	certificate.key_type	certificate.key_length	certificate.exponent	certificate.curve	san.dns	san.uri	san.email	san.ip	basic_constraints.ca	basic_constraints.path_len```

```1620943055.563566	FebYNp2042PTwLAlOf	3	08BB00EE	CN=,OU=,O=,L=,ST=,C=	CN=,OU=,O=,L=,ST=,C=	1432125684.000000	1747485684.000000	rsaEncryption	sha256WithRSAEncryption	rsa	2048	65537	-	-	-	-	-	-	-```

### CODE REVIEW

**Comment by Neo23x0** [comment]
@neu5ron : the fields in the mapping configs for zeek contain dots. Could you look at the rule and check if this would work out? I've never worked with that source and mapping before. 

https://github.com/SigmaHQ/sigma/blob/master/tools/config/ecs-zeek-corelight.yml#L1148

Screenshot 2021-06-23 at 09 14 43

**Comment by neu5ron** [comment]
The zeek source code, website exmaples, ossem, etc all have the dots.
Although this is not to say underscore for these few fields don't exist. But that's post implement specific .. One example can think of is RockNSM. - cc @Neo23x0 


@d4rk-d4nph3 what kind of zeek deployment are you using? Corelight, Security Onion, RockNSM, Malcom, etc...?

**Comment by d4rk-d4nph3** [comment]
@neu5ron, I was directly feeding zeek's logs to my SIEM. My SIEM changes the taxonomy later on.

**Comment by neu5ron** [comment]
ok, makes sense. then I would recommend creating a sigmac for your taxonomy and leveraging that

**Comment by Neo23x0** [comment]
@neu5ron You mean, " creating a sigmac config for", right?

**Comment by Neo23x0** [comment]
So, if other rules for zeek data contain a "." in their field names and this one contains a "_", shouldn't this rule use "." as well?

**Comment by neu5ron** [comment]
@Neo23x0  yes you are correct, the fields in the rule should use `.` 

sorry, - thought this was a PR for corrections, not an entirely new rule with remarks

**Comment by d4rk-d4nph3** [comment]
@Neo23x0 @neu5ron , Sorry for the trouble.

**Comment by neu5ron** [comment]
not a problem!

**Comment by Neo23x0** [comment]
Thanks

**Pull request merged**
