### PR TITLE
Add sysmon_status and sysmon_error category to thor logsource; logical rule fix

### PR DESCRIPTION
**Pull request by phantinuss**

### CODE REVIEW

**Review by frack113 — CHANGES_REQUESTED** [review]
Hi this cant be a `or` otherwise all event eventid 12 or 13 will make a alert

**Comment by Neo23x0** [comment]
It's completely wrong to use EventIDs in generic rule categories. I thought that we had a check for that.

**Comment by Neo23x0** [comment]
If you'd like, you could write a test that checks if a rule uses `category` in their log sources section and `EventID` in the detection section. This should never be the case. 

Rule written for a generic `category` should always get their `EventID`s from the mapping in the configs.

**Review by frack113 — APPROVED** [review]

**Comment by phantinuss** [comment]
@frack113: Sorry nonetheless. I don't know why I misread the rule.

**Pull request merged**
