### PR TITLE
Split some Global builtin

### PR DESCRIPTION
**Pull request by frack113**
Hi,
Split 5 more global rules before weekend :beer:

### CODE REVIEW

**Comment by Neo23x0** [comment]
Awesome

**Comment by frack113** [comment]
I have go back to draft because of the invoke__obfuscation_* .
One part use `driver_load` and `ImagePath` instead of `ImageLoaded`.
When I read some threat hunting on internet , eventID 7045  is 'convert' to a sysmon 13:
 `TargetObject:HKLM\System\CurrentControlSet\Services\*\ImagePath` and ImagePath value is in the `Details`
So not sure the driver_load rule are good event if I change the field name.

**Comment by Neo23x0** [comment]
Strange. I can't see the commits. I only get 404 pages while clicking on the links in this page.

**Comment by Neo23x0** [comment]
Ah, I can see them in the "Commits" tab

**Comment by Neo23x0** [comment]
Correct - it should've been `ImageLoaded`

image

And the `EventID` should also be removed.

**Comment by Neo23x0** [comment]
Drop the `driver_load` rules. I don't that that they make sense.

**Comment by frack113** [comment]
It done, All the win_invoke_obfuscation are split and the driver load rule remove

**Comment by frack113** [comment]
HI,
view that security 4697 is `ServiceFileName` not ImagePath...
Do you think the win_invoke_obfuscation_via_* rule with security chanel are good if I change to the correct fieldname ?

**Comment by frack113** [comment]
Make some test on my Vm.
The detections were false , it is a 'simple' process creation rule not a service log
image

**Comment by frack113** [comment]
This is a big cleanup of  invalid detection in the end.

**Pull request closed without merging**
