### PR TITLE
proc_creation_win_exeute_payload_bypass_wdac_policies.yml

### PR DESCRIPTION
**Pull request by MeshalKSA**
The new sigma rule refers to  Usecase: Execute proxied payload with Microsoft signed binary to bypass WDAC policies. 
Ref URL --> https://lolbas-project.github.io/lolbas/OtherMSBinaries/Wfc/

### CODE REVIEW

**Comment by frack113** [comment]
Hi,
There are already 2 generic rules :
rules/windows/process_creation/proc_creation_win_lolbin_wfc.yml (49be8799-7b4d-4fda-ad23-cafbefdebbc5)
rules/windows/process_creation/proc_creation_win_lolbin_fsharp_interpreters.yml (b96b2031-7c17-4473-afe7-a30ce714db29)

**Comment by MeshalKSA** [comment]
> Hi,
> 
> There are already 2 generic rules :
> 
> rules/windows/process_creation/proc_creation_win_lolbin_wfc.yml (49be8799-7b4d-4fda-ad23-cafbefdebbc5)
> 
> rules/windows/process_creation/proc_creation_win_lolbin_fsharp_interpreters.yml (b96b2031-7c17-4473-afe7-a30ce714db29)
> 
> 

I have created this detection base on the no Sigma rule mentioned on the lolbas-project yet (above link). I think by including all <execute payload>parameters, the rule will be more generic and have comprehensive detection.

**Comment by frack113** [comment]
Hi,
the sigma rule ref are waitting in the PR  : 
 - https://github.com/LOLBAS-Project/LOLBAS/pull/226
 - https://github.com/LOLBAS-Project/LOLBAS/pull/225
 - https://github.com/LOLBAS-Project/LOLBAS/pull/223

Try the rule with aurora (fix errors : double status, references not a list).
[wfc.exe c:\path\to\test.xoml](https://bohops.com/2020/11/02/exploring-the-wdac-microsoft-recommended-block-rules-part-ii-wfc-fsi/) was not detected by your rule but get alerts from: 
- public\windows\process_creation\proc_creation_win_lolbin_wfc.yml
- public\windows\file_event\file_event_win_csharp_compile_artefact.yml

**Review by MeshalKSA — COMMENTED** [review]
Adding patch c:\path\to\test.xoml

**Comment by frack113** [comment]
It is more like
```Yaml
detection:
  select_wfc:
   Image|endswith: '\wfc.exe'
   CommandLine|contains: '.xoml'
  select_fsi:
    Image|endswith:
      - '\fsi.exe'
      - 'fsianycpu.exe'
    CommandLine|contains:
      - '.fsscript'
      - '.fsx'
  condition: 1 of select*
```
`CommandLine` is what is type in the cmd to start, not what is in the file

**Comment by MeshalKSA** [comment]
I have noticed this error on Sigma Rule Test ---> **Error: Process completed with exit code 1,**  
can someone tell me if this error is related to the rule or the failure on script jobs task?

**Comment by frack113** [comment]
The pattern for a valid file name is \'[a-z0-9_]{10,70}\.yml\' .
So should be like `proc_creation_win_lolbin_proxied_payload_script.yml`
start with `proc_creation_win_` like  other in the folder and `.yml` as file extension

**Review by MeshalKSA — COMMENTED** [review]
Remove tags : ds0017,0009

**Review by MeshalKSA — COMMENTED** [review]
Review changes

**Review by MeshalKSA — COMMENTED** [review]
Review changes

**Comment by nasbench** [comment]
Hi,

As stated by @frack113 at the start the rules [Use of Wfc.exe](https://github.com/SigmaHQ/sigma/blob/320ddcb6761a38d3122f74a2e9a2c04830b85422/rules/windows/process_creation/proc_creation_win_lolbin_wfc.yml) and [Use of FSharp Interpreters](https://github.com/SigmaHQ/sigma/blob/0db42c0ca68ad6fcb40de27bd2ca3be18b2f8da2/rules/windows/process_creation/proc_creation_win_lolbin_fsharp_interpreters.yml) already cover the usage case in generic form. 

In the LOLBAS project, the given example `wfc.exe c:\path\to\test.xoml` is just a generic example where the path to the ".xoml" file can be anything and can't be used as it is in the rule.

What I suggest is you try to add other paths in the command line to increase the severity of it and make different from the one that already exists. 

So an example would be like this 

```yml
title: WFC Execution From Suspicious Paths
id: 07b9cc6d-a6cb-49e6-b3ab-463b1632d766
status: experimental
description: Detects execution of WFC.exe binary pointing to a ".xoml" file located in a suspicious location 
references:
    - https://lolbas-project.github.io/lolbas/OtherMSBinaries/Wfc/
tags:
    - attack.t1127
author: Meshal Aljohani
date: 2022/07/17
modified: 2022/07/27
logsource:
    category: process_creation
    product: windows
detection:
    selection_img:
        - Image|endswith: '\wfc.exe'
        - OriginalFileName: 'wfc.exe'
    selection_cli:
        CommandLine|contains:
            - 'C:\Users\Public\'
            - '\AppData\Local\Temp\'
            - '\Desktop\'
            - 'C:\Windows\Temp\'
    condition: all of selection_*
fields:
    - CommandLine
    - ParentImage
falsepositives:
    - Unknown
level: high
```

You add more suspicious paths and do the same for `fsianycpu` and `fsi`

**Comment by nasbench** [comment]
Ping @MeshalKSA 

Any updates regarding this PR?

**Comment by nasbench** [comment]
Closing this PR for now due to inactivity.

**Pull request closed without merging**
