### PR TITLE
Add Provider_Name for EventID

### PR DESCRIPTION
**Pull request by frack113**
To have a better detection

### CODE REVIEW

**Comment by redsand** [comment]
FYI this data is a duplicate of what service: security provides for a lot of backends currently configured in the config/*.yml.  1 example is zircolite.yml, another with arcsight, and hawk.yml

**Comment by frack113** [comment]
It is because I build zircolte.yml (WIP) to avoid FP, I start to add Provider_Name to Eventid.
For the moment find already 4 Provider_Name for the security Channel.
Add I stop the count at 20 for Application Channel.

An analogy could be  EventID is the house number , Provider_Name the street name, Channel the city name.

For sysmon , there is only 1 Provider_Name for the channel, so you can use one or the other...

I have look hawk.yml ,`product_name` looks like the Channel only.

**Comment by redsand** [comment]
Can you provide an example log output?  I dont recall seeing Provider_Name as a value field in m$ eventlog and my only concern is that it will cause a lot of things to never match.

**Comment by frack113** [comment]
In microsoft documentation [System part](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-1102)
```xml
<System>
 <Provider Name="Microsoft-Windows-Eventlog" Guid="{fc65ddd8-d6ef-4962-83d5-6e5cfe9ce148}" /> 
 <EventID>1102</EventID> 
 <Version>0</Version> 
 <Level>4</Level> 
 <Task>104</Task> 
 <Opcode>0</Opcode> 
 <Keywords>0x4020000000000000</Keywords> 
 <TimeCreated SystemTime="2015-10-16T00:39:58.656871200Z" /> 
 <EventRecordID>1087729</EventRecordID> 
 <Correlation /> 
 <Execution ProcessID="820" ThreadID="2644" /> 
 <Channel>Security</Channel> 
 <Computer>DC01.contoso.local</Computer> 
 <Security /> 
 </System>
```
space are replace by '_' in sigma field name rule.
Zircolite manage very well this part .
Winlogbeat get a winlog.provider_name.
try nxlog CE and get a SourceName (Why change the name ?).

Some rule use this `Keywords` field.

**Comment by redsand** [comment]
Ok, thanks for confirming it won't break existing signatures.  I am still not sold on why it adds any value.  I have never seen a conflict on the old eventlog subsystem (pre vista/win7) and so I don't see what problem is being solved or value added, but rather duplicate.  Can you share with me the conflict example that this problem solves?  Sorry to be a bother, I just dont want an additional analytic check, if it's already duplicate.  I haven't seen this pain in our deployment, and the rules are currently applied to an environment of ~100k eps avg

**Comment by frack113** [comment]
Zicolite and a sandbox evtx malware (invoice.exe 😄) . Sorry Get only the picture left.
First without Provider_name, second with Provider_name
Malware_facture

By digging ETW , Seen there should not be overlap in the security chanel , but in application there is.

**Comment by redsand** [comment]
Okay, I agree that there could be overlap between Application and System.  I think the commits only provide updates to Security and Sysmon?

**Comment by frack113** [comment]
Will redo it some day only for application and system channel.

**Comment by redsand** [comment]
much love!

**Pull request closed without merging**
