### PR TITLE
Update proc_creation_win_persistence_userinitmprlogonscript.yml

### PR DESCRIPTION
**Pull request by branchnetconsulting**
### Summary of the Pull Request

This PR enhances the logon scripts rule

### Detailed Description of the Pull Request / Additional Comments

- Add `powershell.exe` as an optional filter for Windows Core machines. Since it's the default shell.
- Split the logon script rules into 2 different rules

### Example Log Event

N/A

### Fixed Issues

N/A

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by nasbench** [comment]
Can you please provide a public reference to this?

**Comment by branchnetconsulting** [comment]
Hi, this link describes how you can manage Server Core systems via Remote Desktop.  When you remote desktop into Server Core (once it has been enabled), it serves up nothing but a Powershell window inside of the RDP session.   That process of logging in and being served up a Powershell window, involves userinit.exe calling powershell.exe without any parameters.  One of my clients has some Server Core systems running Sysmon and throwing events like this that are tripping this Sigma rule when an admin RDPs into one of those Server Core systems.  No login script is involved.   I do not have any formal documentation about that but hope this link helps:
https://www.prajwaldesai.com/enable-remote-desktop-on-windows-server-core/

**Comment by nasbench** [comment]
Thanks for the link, its a good start. I will look into this more and report back.

**Comment by branchnetconsulting** [comment]
In case it is helpful, here is an example Sysmon record that presently trips this Sigma rule while all that is happening is an admin user RDPing into a Server Core system.

Process Create:
RuleName: technique_id=T1059.001,technique_name=PowerShell
UtcTime: 2023-05-26 19:15:03.259
ProcessGuid: {d89c6cc7-0537-6471-fb00-000000002400}
ProcessId: 2136
Image: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
FileVersion: 10.0.17763.1 (WinBuild.160101.0800)
Description: Windows PowerShell
Product: Microsoft® Windows® Operating System
Company: Microsoft Corporation
OriginalFileName: PowerShell.EXE
CommandLine: PowerShell.exe
CurrentDirectory: C:\Windows\system32\
User: DOMAIN\admin-user
LogonGuid: {d99c6cd7-0525-6471-292a-550000000000}
LogonId: 0x542A39
TerminalSessionId: 3
IntegrityLevel: High
Hashes: SHA1=6CBCE4A295C163791B60FC23D285E6D84F28EE4C,MD5=7353F60B1739074EB17C5F4DDDEFE239,SHA256=DE96A6E69944335375DC1AC238336066889D9FFC7D73628EF4FE1B1B160AB32C,IMPHASH=741776AACCFC5B71FF59832DCDCACE0F
ParentProcessGuid: {d89c6cc7-0537-6471-f900-000000002400}
ParentProcessId: 5296
ParentImage: C:\Windows\System32\userinit.exe
ParentCommandLine: C:\Windows\system32\userinit.exe
ParentUser: DOMAIN\admin-user

**Review by nasbench — APPROVED** [review]

**Review by phantinuss — APPROVED** [review]

**Pull request merged**
