### PR TITLE
fix: updated targetUserName and ipAddress

### PR DESCRIPTION
**Pull request by qasimqlf**

### CODE REVIEW

**Comment by nasbench** [comment]
Please provide the log that prompted the fix. So we can double-check.

**Comment by qasimqlf** [comment]
This is the event log of already mentioned reference, you can verify it.

https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES/blob/master/Privilege%20Escalation/4624%20LT3%20AnonymousLogon%20Localhost%20-%20JuicyPotato.evtx


Here you can see 4624 with Anonymous Logon, not having _. And also read the last reply of that tweet in reference.

image

**Comment by nasbench** [comment]
> @nasbench This is the event log of already mentioned reference, you can verify it.
> 
> https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES/blob/master/Privilege%20Escalation/4624%20LT3%20AnonymousLogon%20Localhost%20-%20JuicyPotato.evtx
> 
> Here you can see 4624 with Anonymous Logon, not having _. And also read the last reply of that tweet in reference.
> 
> image

Alright. Next time better include information about the PR in the description of the PR itself. To make it easy/quick to review ;)

**Review by nasbench — APPROVED** [review]

**Comment by qasimqlf** [comment]
Will remember next time.

**Pull request merged**
