### PR TITLE
Add registry_set_disable_winevt_logging

### PR DESCRIPTION
**Pull request by frack113**
More generic than the ransomware as there are many channel 😄

### CODE REVIEW

**Comment by nasbench** [comment]
We do have a pretty similar one in private I believe.

cc @Neo23x0

**Comment by Neo23x0** [comment]
Yes, maybe we should merge both rules and remove our internal rule. 
We should include the filters that @frack113 has defined.

**Comment by frack113** [comment]
The filter are to pass the good dataset (Even the win11 I have made ).
I set `medium` as it is any channel to keep `high` for  important one

**Comment by nasbench** [comment]
In the internal version we found was "wevtutil.exe" was setting the enabled "key" to 0 during the installation of manifests so we excluded that and we filtered on that instead of those specific channels.

**Comment by frack113** [comment]
I saw it, but after I thought it was too loose for the filter.
Don't want to leave a hole on "wevtutil.exe" use.

**Comment by nasbench** [comment]
The issue that I feared was that we'll probably have these kind of FP from "wevtutil" during updates for manifests and installation of new manifests. The registry event doesn't contain enough information that'll make us find the difference between susp usage and legitimate usage.

I decide to filter it out since we already have good coverage of disabling event logs via "wevtutil"

**Comment by frack113** [comment]
I let you see if you close it or update it with the internal one.

**Comment by nasbench** [comment]
I think it's better we merge them and make the rule public. I'll push the changes and let me know what you think of them.

**Review by Neo23x0 — APPROVED** [review]

**Pull request merged**
