### PR TITLE
Create okta_detect_suspicious_push_challenge.yml

### PR DESCRIPTION
**Pull request by austinsonger**
### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by austinsonger** [comment]
@frack113 it's been awhile for me.

I need to refresh some of knowledge you have any example of sequence detections? This is how my rule would look in Elastic Security.

```
sequence with maxspan=10m
    [event.dataset:okta.system and event.action:system.push.send_factor_verify_push]
    [event.dataset:okta.system and event.action:user.authentication.auth_via_mfa and okta.debug_context.debug_data.factor:OKTA_VERIFY_PUSH]
```

**Comment by frack113** [comment]
hi,
It is the `near` condition with [timeframe](https://github.com/SigmaHQ/sigma-specification/blob/main/Sigma_specification.md#timeframe).
These rules have been moved to the unsupported folder.
[exemple of near with timeframe](https://github.com/SigmaHQ/sigma/blob/master/unsupported/windows/proc_creation_win_correlation_apt_turla_commands_medium.yml)

We are **working** on https://github.com/SigmaHQ/sigma-specification/blob/version_2/Sigma_meta_rules.md.

For X events in a timeframe : https://github.com/SigmaHQ/sigma-specification/blob/version_2/Sigma_meta_rules.md#temporal-proximity-temporal

You can do this one  in the `unsupported/cloud` to keep a track.

**Comment by frack113** [comment]
Should be like this
```yaml
    selection_1:
        action: system.push.send_factor_verify_push
    selection_2:
        action: user.authentication.auth_via_mfa
        okta.debug_context.debug_data.factor: OKTA_VERIFY_PUSH
    timeframe: 10m
    condition: selection_1 | near selection_2
```

**Comment by nasbench** [comment]
Just FYI @austinsonger rules using the old sigmac notation aren't accepted in SIGMA HQ anymore.

Since we're transitioning to PySIGMA we've removed any dependency on the old sigmac including the old correlations.

**Comment by nasbench** [comment]
Closing this as a not possible for now as correlation of pysigma are not yet implemented. Will migrate once its in prod

**Pull request closed without merging**
