### PR TITLE
feat: add missing `OriginalFileName` field

### PR DESCRIPTION
**Pull request by qasimqlf**
Adding `OriginalFileName` fields for different images

### CODE REVIEW

**Comment by nasbench** [comment]
@qasimqlf APT and malware rules are explicitly not using OFN as they are specific to the threat. No need to detect renamed version as it would be another thing.

**Comment by qasimqlf** [comment]
> @qasimqlf APT and malware rules are explicitly not using OFN as they are specific to the threat. No need to detect renamed version as it would be another thing.

I am updating mostly process_creation rules

**Comment by nasbench** [comment]
These shouldn't have their OFN updated

- proc_creation_win_apt_zxshell.yml
- proc_creation_win_malware_notpetya.yml
- proc_creation_win_redmimicry_winnti_proc.yml

**Comment by qasimqlf** [comment]
@nasbench  Ok, then how can i see this thing either OFN need to be updated or not? 

Any trick?

**Comment by qasimqlf** [comment]
Created another one for this

**Pull request closed without merging**
