### PR TITLE
reducing level due to low indicator, per devops processes

### PR DESCRIPTION
**Pull request by redsand**

### CODE REVIEW

**Comment by Neo23x0** [comment]
I'd probably like to split that rule up into two. Which parts of the selection did you see produce many false positives? 
e.g. I don't expect the `convertto-securestring` in the command line to produce many FPs.

**Comment by redsand** [comment]
Great catch.  I've split this rule out into two separate rules.  ConvertTo-SecureString now has its own dedicated detection.

**Comment by frack113** [comment]
What do you think of this refractor
```yaml
detection:
  selection_to_1:
    Image|endswith: '\powershell.exe'
    CommandLine|contains:
      - 'ToInt'
      - 'ToDecimal'
      - 'ToByte'
      - 'ToUint'
      - 'ToSingle'
      - 'ToSByte'
  selection_to_2:
    CommandLine|contains:
      - 'ToChar'
      - 'ToString'
      - 'String'
  selection_gen_1:
    Image|endswith: '\powershell.exe'
    CommandLine|contains|all:
      - 'char'
      - 'join'	  
  selection_gen_2:
    Image|endswith: '\powershell.exe'
    CommandLine|contains|all:
      - 'split'
      - 'join'
  selection_gen_3:
    Image|endswith: '\powershell.exe'
    CommandLine|contains|all:
      - 'ForEach'
      - 'Xor'
  condition:  all of selection_to_* or 1 of selection_gen_*
```

**Comment by redsand** [comment]
> What do you think of this refractor
> 
> ```yaml
> detection:
>   selection_to_1:
>     Image|endswith: '\powershell.exe'
>     CommandLine|contains:
>       - 'ToInt'
>       - 'ToDecimal'
>       - 'ToByte'
>       - 'ToUint'
>       - 'ToSingle'
>       - 'ToSByte'
>   selection_to_2:
>     CommandLine|contains:
>       - 'ToChar'
>       - 'ToString'
>       - 'String'
>   selection_gen_1:
>     Image|endswith: '\powershell.exe'
>     CommandLine|contains|all:
>       - 'char'
>       - 'join'	  
>   selection_gen_2:
>     Image|endswith: '\powershell.exe'
>     CommandLine|contains|all:
>       - 'split'
>       - 'join'
>   selection_gen_3:
>     Image|endswith: '\powershell.exe'
>     CommandLine|contains|all:
>       - 'ForEach'
>       - 'Xor'
>   condition:  all of selection_to_* or 1 of selection_gen_*
> ```

brilliant

**Comment by frack113** [comment]
Sorry very bad cut and paste

**Review by frack113 — APPROVED** [review]

**Comment by Neo23x0** [comment]
Would the level with the changes proposed by Frack113 then still be "low" or should we raise it to "medium" again?

**Comment by frack113** [comment]
selection_gen_1 : low - seem very generic text manipulation
selection_gen_2 : low - seem very generic  text manipulation 
selection_gen_3 : medium - who need to do `xor` for administration

**Pull request merged**
