### PR TITLE
Added win_ad_find_discovery.yml

### PR DESCRIPTION
**Pull request by blueteam0ps**
Rule to detect the most commons switches used in AdFind tool

### CODE REVIEW

**Comment by Neo23x0** [comment]
Couldn't we put spaces around each expression? 
E.g. "odmp" or "dclist" could appear in bigger statements or base64 encoded command line parameters.

**Comment by blueteam0ps** [comment]
@Neo23x0  - what do you mean with regard to spaces?

**Comment by Neo23x0** [comment]
From `oudmp` to ` oudmp `

**Comment by Neo23x0** [comment]
Ping @blueteam0ps

**Pull request merged**
