### PR TITLE
Create azure_app_logout_url.yml

### PR DESCRIPTION
**Pull request by MarkMorow**
Adding Logout URL modification

### CODE REVIEW

**Comment by frack113** [comment]
hi , it is a duplicate of azure_app_appid_uri_changes.yml

**Comment by MarkMorow** [comment]
Hi, you are correct. In the audit logs the audit Activity message is the same. The actually value in the modified properties is different and will depend on the application. What's the best way to structure this rule then? This is a very low risk event so if I had to pick one I'd pick the AppID_URI.

**Comment by frack113** [comment]
If is it a realy a low risk event , make a update to azure_app_appid_uri_changes.yml to change the `level` to `medium` (add `modified:` too) .
from what I read AppID_URI is unique and random, so it's hard to write a rule with it.

**Comment by MarkMorow** [comment]
If the AppID URI is changed that's a really big issue. I'll leave that one at high as it is. Let me think about this logout URL one for a bit to see if there is a better way to do it.

**Comment by MarkMorow** [comment]
Since this is a low impact I will close this request until there is a more granular way to look for this.

**Pull request closed without merging**
