### PR TITLE
Update proc_creation_win_hktl_winpeas.yml

### PR DESCRIPTION
**Pull request by gs3cl**
### Summary of the Pull Request

Enhance the winpEAS detection rule due to customer experience regarding possible false positives

### Detailed Description of the Pull Request / Additional Comments
- add WSL part
- format changed

The follow sysmon config was used for testing
https://github.com/ion-storm/sysmon-config/blob/master/sysmonconfig-export.xml

Event wil lbe triggered due to Option `-linpeas`

raw log WinPEAS

```
 Looking for Linux shells/distributions - wsl.exe, bash.exe
    C:\Windows\System32\wsl.exe
    C:\Windows\System32\bash.exe

    Found installed WSL distribution(s) - listed below
    Run linpeas.sh in your WSL distribution(s) home folder(s).

    Distribution:      "Ubuntu-20.04"
    Root directory:    "C:\Users\gs3cl\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04LTS_79rhkp1fndgsc\LocalState\rootfs"
    Run command:       wsl.exe --distribution "Ubuntu-20.04"
   =================================================================================================

  Running linpeas.sh in the default distribution
  Using linpeas.sh URL: https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh
```

### Example Log Event

```
Process Create:
RuleName: Attack=T1202,Technique=Indirect Command Execution,Tactic=Execution,DS=Process: Process Creation,Level=0,Desc=Windows Subsystem For Linux,Risk=20
UtcTime: 2023-03-20 19:51:50.902
ProcessGuid: {fbe2d581-b956-6418-4014-000000002300}
ProcessId: 32496
Image: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.3.0_x64__8wekyb3d8bbwe\wsl.exe
FileVersion: 1.1.3.0
Description: Windows Subsystem for Linux
Product: Windows Subsystem for Linux
Company: Microsoft Corporation
OriginalFileName: wsl.exe
CommandLine: "bash" -c "curl https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh --silent | sh"
CurrentDirectory: C:\Users\gs3cl\Downloads\
User: DESKTOP-Victim\gs3cl
LogonGuid: {fbe2d581-9eee-6418-f305-7c1600000000}
LogonId: 0x167C05F3
TerminalSessionId: 5
IntegrityLevel: High
Hashes: SHA1=DBED8A6BB72506096516EEA167375B342BA28978,MD5=9793CEE9A6510B6B541612026BF4AAB0,SHA256=56187B1998193DDB24EED8C88F0FCC0AC03BF92865AFFA85667A2382626F6257,IMPHASH=6FE80D78AF20C868296D8CA97AC88CE0
ParentProcessGuid: {fbe2d581-b956-6418-3e14-000000002300}
ParentProcessId: 14940
ParentImage: C:\Windows\System32\bash.exe
ParentCommandLine: "bash" -c "curl https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh --silent | sh"
ParentUser: DESKTOP-Victim\gs3cl
```

Example Splunk SPL:

```
(Image IN ("*\\winPEASany.exe", "*\\winPEASany_ofs.exe", "*\\winPEASx64.exe", "*\\winPEASx64_ofs.exe", "*\\winPEASx86.exe", "*\\winPEASx86_ofs.exe") OriginalFileName="winPEAS.exe") OR (Image IN ("*\\winPEASany.exe", "*\\winPEASany_ofs.exe", "*\\winPEASx64.exe", "*\\winPEASx64_ofs.exe", "*\\winPEASx86.exe", "*\\winPEASx86_ofs.exe") OriginalFileName="winPEAS.exe" CommandLine IN ("* domain*", "* systeminfo*", "* userinfo*", "* processinfo*", "* servicesinfo*", "* applicationsinfo*", "* windowscreds*", "* browserinfo*", "* filesinfo*", "* fileanalysis*", "* eventsinfo*")) OR (Image="\\WindowsApps\\MicrosoftCorporationII.WindowsSubsystemForLinux_*" Image="*\\wsl.exe" OriginalFileName="wsl.exe" CommandLine="*\"bash\"*" CommandLine="*-c*" CommandLine="*curl*" CommandLine="*https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh*" CommandLine="* ---silent | sh*")
```

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

Regards,

### CODE REVIEW

**Comment by nasbench** [comment]
That's a pretty drastic change from the intention of the rule. 

- The choice of the CLI option was meant to look for stuff events without the image names. Hence the smaller selection of flags. Now it's an `and` which makes the rule less broad.
- The `OriginalFileName` is an `or` with the image and not an `and`
- The WSL selection could be broader by only looking for the URL for example. Since other variations of download and execution could be used. Example: `bash`, `wget`...etc.
- Also the `Image|endswith: '\wsl.exe'` is enough no need for the startswith.

**Comment by gs3cl** [comment]
Hey nasbench,

thanks for your input I did some updates.

Regards

**Comment by nasbench** [comment]
@gs3cl It still needs some updates. I will update it later today.
I will ping you when it's done.

**Comment by gs3cl** [comment]
> @gs3cl The idea behind `selection_cli_option` was and still is to trigger the rule only on options without the need for Image or OriginalFIleName. So we need to choose specific ones.
> 
> Also, I removed the dependency on `bash` since from your log a CLI ending with 'linpeas' is specific for this tool imho.
> 
> One last thing before I approve this. Can you check the author field? Is that meant to be your username? If so then please separate it by a `,`

thats fine I changed the format thats my name and employer :) Thanks for help

**Review by nasbench — APPROVED** [review]

**Review by phantinuss — APPROVED** [review]

**Pull request merged**
