### PR TITLE
Add DLL Sideloading of NickelLoader Malware Loader

### PR DESCRIPTION
**Pull request by ThureinOo**
### Summary of the Pull Request
This PR contains a new  detection related to DLL Sideloading used by Lazarus APT

### Changelog
new: Lazarus APT DLL Sideloading Activity

### Example Log Event
N/A

### Fixed Issues
N/A

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by nasbench** [comment]
Please @ThureinOo read the conventions and the error messages before opening a PR to ease the process of review :) and if your PR is work in progress open it as draft.

Every time you're submitting a PR we have to fix almost everything :) 

- The order of the fields needs to be respected. User other rules as reference
- The indentation needs to be 4 spaces
- The rule you provided is specific to the malware at this point so move it to Emerging threat and follow the conventions of similar ET rules. Or you can do more research and turn it into a generic rule

**Comment by ThureinOo** [comment]
Hi @nasbench , Thanks for understanding me. The automated checks happens when I created pull request and I only find errors at that time. Is there any way to check without making a pull request? I think I can't make automated check in my forked repo. Also the test_script.py is not working on my machine and that is why. I am really sorry if I made you feel any annoy.

**Comment by ThureinOo** [comment]
image

This is the error i  received when i run the script. I even downloaded the thor.yml and no works. I firstly created this rule in socprime console and i think there might have indentation difference between the platforms.

**Comment by nasbench** [comment]
> image
> 
> This is the error i received when i run the script. I even downloaded the thor.yml and no works. I firstly created this rule in socprime console and i think there might have indentation difference between the platforms.

It looks like there is a bug in the test when run from anywhere other than the root. Will fix it later.

As for the indentation. VsCode should take of it. In your case the description was carried into a new line.

**Comment by ThureinOo** [comment]
Hi @nasbench , so does it mean I cannot run the script locally currently and I need to wait for the updated script? Thanks.

**Comment by nasbench** [comment]
> Hi @nasbench , so does it mean I cannot run the script locally currently and I need to wait for the updated script? Thanks.

You can run it now by executing it from inside the test folder. The bug is that it's using a relative path `../tests/thor.yml` so adapt to it for now.

There's a fix that will ignore the test in case of errors in another PR.

**Comment by nasbench** [comment]
@ThureinOo Why did you delete the PR????? Are you wasting everybody's time or what???!!!

**Comment by ThureinOo** [comment]
Ah, @nasbench ,  when i need to add new file, I thought i need to refork the sigmahq repo and i deleted the old repo, and this case is unintentionally closed now. How can i do that? do i need to recreate the rule? `image_load_malware_nickelLoader_side_load_mscoree.yml` .

**Comment by nasbench** [comment]
I copied them into another PR.

@ThureinOo Please refrain from doing such things again as its time consuming for everyone :)

Git offers a solutions in the form of branches where you can create as many branches as you like. Give this tutorial a read to get familiar https://git-scm.com/docs/gittutorial

**Comment by ThureinOo** [comment]
Thanks @nasbench I will look into it , Btw, can you please help me to fix the error `error    wrong new line character: expected \n  (new-lines)` on the first line when i check yamllint. I can't find the right fix for this.

**Pull request closed without merging**
