### PR TITLE
Add alterix to Projects or Products that use Sigma Rules

### PR DESCRIPTION
**Pull request by mtnmunuklu**
### Summary of the Pull Request

Add [alterix](https://github.com/mtnmunuklu/alterix) to Projects or Products that use Sigma Rules

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

### CODE REVIEW

**Comment by nasbench** [comment]
As this is a repo for rules and not the library. This doesn't qualify to be on the list as its just converting Sigma rules not using them. Its best to add CRYPTTECH's SIEM instead of this tool.

**Comment by mtnmunuklu** [comment]
> As this is a repo for rules and not the library. This doesn't qualify to be on the list as its just converting Sigma rules not using them. Its best to add CRYPTTECH's SIEM instead of this tool.

Thank you for the prompt response. I don't have specific information about when the integration of CRYPTTECH SIEM and SIGMA will be completed. We can close the PR. I can reopen the PR once the integration is completed.

**Review by nasbench — APPROVED** [review]

**Comment by nasbench** [comment]
If that's the case then we can leave it for now. Please update this entry once the integration is complete :)

**Comment by mtnmunuklu** [comment]
> If that's the case then we can leave it for now. Please update this entry once the integration is complete :)

Thank you, Sure

**Pull request merged**
