### PR TITLE
Update another command line of Get-WmiObject (gwmi)

### PR DESCRIPTION
**Pull request by nNipsx-Sec**
Update another command line of Get-WmiObject (gwmi)

### CODE REVIEW

**Comment by frack113** [comment]
HI,
Thanks for your contribution.
As detection change, `modified`  have to be update too.

**Comment by nNipsx-Sec** [comment]
Can you add field Author Contribute in this rules thanks 👍

**Comment by Neo23x0** [comment]
Adding yourself to the `author` field is okay. We need no additional field.

**Comment by nNipsx-Sec** [comment]
Thanks, it's clear !

**Pull request merged**
